### ISSUE TITLE
Hi I guess this is the project I (gcolgate@gmail.com) was interested to find

### ISSUE THREAD

**Issue by gilcolgate3** [a-b-street/abstreet#1000]

**Comment by dabreegster** [comment]
Hi, you're interested in the map viewer code? https://a-b-street.github.io/docs/tech/dev/index.html#code-organization gives an overview, but from the bottom-up...

- [widgetry](https://github.com/a-b-street/abstreet/tree/master/widgetry/) is a UI framework and slippy map canvas using OpenGL / WebGL
- [map_gui](https://github.com/a-b-street/abstreet/tree/master/map_gui) takes the "map model" and renders it using widgetry, using quadtrees and batching layers of things on the map to be efficient
- then finally, there are the apps themselves built on top of this, like https://github.com/a-b-street/abstreet/tree/master/apps/osm_viewer

The map model is built from OpenStreetMap data and has many steps. They're now split between https://github.com/a-b-street/osm2streets (the lowest layer) and the [map_model](https://github.com/a-b-street/abstreet/tree/master/map_model) crate. Let me know if I can answer any questions about how things work or where to find some piece of code!
