### ISSUE TITLE
Tutorial Crashed at Task 5

### ISSUE THREAD

**Issue by kchomacau** [a-b-street/abstreet#1001]
How the error comes:
[abstreet.html](http://play.abstreet.org/0.3.34/abstreet.html) > Traffic Simulation Tutorial > Skip to Task 5

Error Message:
<kbd><img width="425" alt="image" src="https://user-images.githubusercontent.com/13083104/194090986-1d3cf56e-475c-4e7b-8737-d2938a511e5a.png"></kbd>

**Comment by dabreegster** [comment]
Thanks! The last release brought in footpaths and changed some hardcoded OSM IDs used in the tutorial. It's relatively straightforward to fix by looking at that line number. I'll get to it when I have time, and in the meantime, you can use the old version: http://play.abstreet.org/0.3.33/abstreet.html?--tutorial=5
Sorry for the hassle and thanks for reporting

**Comment by dabreegster** [comment]
The very last tutorial is still kind of broken, because some parking lanes have been assigned to another side of the street. This is very hard to maintain through improvements to the import process. At least the crash is gone.
