### ISSUE TITLE
Import new area (around Strasbourg - France)

### ISSUE THREAD

**Issue by rouelibre1** [a-b-street/abstreet#1006]
Would it be possible to integrate the area around Strasbourg - France ?

Planning to work on LTN locally and I'd love see what abstreet can do and provide feedback

**Comment by dabreegster** [comment]
Sure! Send a geojson.io/ polygon please. You can also try the import yourself (https://a-b-street.github.io/docs/user/new_city.html#the-easy-method), but use the downloaded version (https://github.com/a-b-street/abstreet/releases/tag/v0.3.34) for that

**Comment by rouelibre1** [comment]
Thank you, I've managed to import a neighborhood into the downloaded app from a geojson area and started to discover the LTN part of the app. For the time being, I think I'm good importing in the UI every time I want to use my area.

I may ask later for a map of my area to be included in the UI, depending on how other bike activists plan on using it locally.

**Comment by dabreegster** [comment]
Awesome, keep me posted how it goes! Depending how dual carriageways and bridges/tunnels in the area work, the default boundaries might be really weird and adjusting could be tough, let me know if you hit problems

**Comment by rouelibre1** [comment]
Re-opening this because we are starting locally to use the tool (LTN module) more intensively with bicycle activists and local authorities : more (non-tech) people will need to be able to manipulate the area, so the manual import will not be enough, also we will need to demonstrate and use the web version with local examples.

Here are 3 json files for the area of interest. 

I'm wondering if the files cover an area of reasonable size to integrate in the tool ?

I've downloaded the multipolygon version from geojson.io, but also split into 3 files as I didn't remember what would be best to implement.
[stb2.json](https://github.com/a-b-street/abstreet/files/12893198/stb2.json)
[stb3.json](https://github.com/a-b-street/abstreet/files/12893199/stb3.json)
[stb1.json](https://github.com/a-b-street/abstreet/files/12893200/stb1.json)



[StbMulti.json](https://github.com/a-b-street/abstreet/files/12893189/StbMulti.json)

**Comment by XioNoX** [comment]
FYI: if it helps I sent PR #1126 to add the relevant GTFS.

**Comment by rouelibre1** [comment]
I beliebe it's ok to implement this way.

Just to mention it, i am indeed experiencing some hiccups with the auto-detected boundaries Visually it seems similar to https://github.com/a-b-street/abstreet/issues/1087

![image](https://github.com/a-b-street/abstreet/assets/73238613/ad40c628-7373-4c48-9ad6-ca95398ed792)

**Comment by dabreegster** [comment]
A new release has these maps: https://play.abstreet.org/0.3.49/ltn.html?system/fr/strasbourg/maps/center.bin

There hasn't been recent work on the auto-detected boundaries, so I'm not surprised there are more problems here. The only news is that I started prototyping a very different approach to the LTN tool. Setting boundaries is hopefully simpler. Still cases with bridges and tunnels are a bit weird, but I have more confidence we can solve them with the new approach. You can preview the new one at https://dabreegster.github.io/ltn, but it's very early days still

**Comment by rouelibre1** [comment]
Thanks a lot for the release !

Is there a chance your could help me understand what's going on with the area in the screenshot above ?

I suspect the OSM data of the area is probably involved and I'd be happy to help clean it, but I don't know where to start looking.

The "adjust boundary" feature didn't really help in this case, I've been struggling with it yesterday and all I could get as a result is quite poor in terms of coherence (many times I want to select a block but I'm unable to do so until I add another block that is located,,, welle, somewhere else in the area and I can't seem to find a logical pattern to guess in which order blocks need to be added / removed.
![Capture d'écran 2024-01-18 221750](https://github.com/a-b-street/abstreet/assets/73238613/415889ef-fbad-4cb9-8934-e3affb4ed970)

Hope this makes sense

**Comment by rouelibre1** [comment]
Again, it's exciting so see what's coming (including the new walking-focused tool)
Geojson file (github doesn't seem to accept geojson files, so here's a geojson inside a zip) :

[ltn_custom.zip](https://github.com/a-b-street/abstreet/files/14002042/ltn_custom.zip)

It looks fine and I didn't detect any issue in the process : I'm impatient to see this new version grow and evolve!
We'll be sure to try it locally as soon at it's mature enough to share ambitious LTN proposals with the local authorities and the general public.

**Comment by dabreegster** [comment]
Awesome to hear it works, and it's showing up for me too:
![Screenshot from 2024-01-21 21-45-38](https://github.com/a-b-street/abstreet/assets/1664407/36b264c0-3c12-4f98-a75e-9346873d103b)
On the first screen, under Examples, the Strasbourg one should now work (I uploaded the file to the wrong place). And for future reference, I think on GH if you name a geojson file as .txt, it'll work more easily.

Very useful to know the new version can handle this boundary that the old can't. I'll prioritize development of it as much as possible. And you reminded me that sharing the proposals from the tool easily is something to consider, so filed https://github.com/dabreegster/ltn/issues/13

**Comment by rouelibre1** [comment]
Is there an easy way to follow the progress of the new revamped LTN tool ? (and to contribute with feedback, comment, translations, etc)

**Comment by dabreegster** [comment]
I've only been able to spend a day or two per week on it, so it's felt quite tough to get it to some kind of MVP. How about as a simple improvement, I'll start a new GH issue in that repo to summarize recent changes? You can feel free to comment there or raise other issues.

There are big UX / design questions I have that I can ask, and if you have opinions or want to get more involved and sketch a wireframe or something, that could also speed things up! Translations is a very good question -- it'd be better to get that started sooner or later, and I'm hoping it's _much_ easier, since the frontend is now just a web app using a popular framework. Let me start those GH issues and I'll CC you in...

**Comment by dabreegster** [comment]
@rouelibre1, https://github.com/dabreegster/ltn/issues/16 and https://github.com/dabreegster/ltn/issues/17
