### ISSUE TITLE
Crash on loading Lyon Map on 0.3.38

### ISSUE THREAD

**Issue by XaranDeBruregor** [a-b-street/abstreet#1051]
Hello !

The windows application version 0.3.38 crashed when I load Lyon's map on LTN. 

Also tried on the web application : 
![image](https://user-images.githubusercontent.com/98983847/214876241-11ec2941-f8c2-4c15-bf60-306784b624e3.png)

**Comment by Transurgeon** [comment]
I am taking a look into this. 

<img width="611" alt="image" src="https://user-images.githubusercontent.com/89562186/214973492-e381141e-d23f-4c21-b5b3-03aa92da348f.png">

The reason could be because the euclidian distance is calculated instead of the haversine distance which leads to these two specific points to be too close to each other (in the line constructor, the distance must be greater than epsilon which is defined as 0.01 meters). 

However, I still think these points would be too close. Could we somehow delete one of the two points?

**Comment by dabreegster** [comment]
The `raw_dist_to` comment was old and misleading; `Pt2D`s are fine to use Euclidean distance: https://a-b-street.github.io/docs//tech/map/details.html#coordinate-system

Running with `RUST_BACKTRACE=1`, more of the error is:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Line from Pt2D { x: 9868.9908, y: 4474.0891 } t
o Pt2D { x: 9868.994, y: 4474.0986 } too small', geom/src/line.rs:25:29
stack backtrace: 
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: geom::line::Line::must_new
   4: geom::polyline::PolyLine::dist_along_of_point
   5: geom::ring::Ring::get_both_slices_btwn
   6: geom::ring::Ring::get_slice_between
   7: map_model::objects::block::Perimeter::to_block
   8: ltn::partition::Partitioning::seed_using_heuristics
```

The most complex part of the LTN tool divides space between main roads and traces around blocks. After new changes in road geometry from osm2streets in this release, that process is hitting some new problem. I have a few ongoing ideas to make the LTN tool not rely on this brittle and complicated "blockfinding" process, and also try to solve problems @XaranDeBruregor has hit where tunnels/bridges cross. For the moment, looks like you should stick to the 0.3.37 release for the LTN tool, sorry.

The info about the new blockfinding idea is unfortunately a bit scattered in a few places, but if anyone's interested:
https://dabreegster.github.io/talks/aiuk_ltn/slides.html#/defining-a-neighborhood-1
https://github.com/a-b-street/abstreet/issues/1024
https://github.com/a-b-street/abstreet/pull/1044
https://github.com/a-b-street/osm2streets/issues/10
https://github.com/a-b-street/osm2streets/issues/170

It's the most urgent thing on my mind, so trying to make real progress on it

**Comment by dabreegster** [comment]
![Screenshot from 2023-02-09 11-50-31](https://user-images.githubusercontent.com/1664407/217805154-e7a70a56-2e19-479f-9197-fa70ef69ce89.png)
I've tried disabling some of the epsilon checks, just to see what's causing trouble over here. I can't even figure out the problem -- it looks completely fine.

Going to start a PR suggesting a pretty radical change to the geom library...

**Comment by XaranDeBruregor** [comment]
My small update on the issue. Tested with abstreet_windows_v0_3_39, also not working. 
I saw your progress on the subject. That's great work ! Cheers. :D

**Comment by dabreegster** [comment]
This particular problem will be fixed in the next release (hopefully next few days), though editing boundaries is still broken in Lyon

**Comment by dabreegster** [comment]
http://play.abstreet.org/0.3.40/ltn.html?system/fr/lyon/maps/center.bin
Give 0.3.40 a shot. It at least doesn't crash, but you can't edit boundaries here yet, due to some bizarre still unsolved problem

**Comment by dabreegster** [comment]
0.3.41 should also let you edit boundaries in Lyon now, FYI

**Comment by XaranDeBruregor** [comment]
Yep I confirm with 0.3.41, boudaries editing is baack !
