### ISSUE TITLE
crash on loading low traffic neighbourhoods

### ISSUE THREAD

**Issue by Transurgeon** [a-b-street/abstreet#1052]
The output of the crash is detailed here: [output.txt](https://github.com/a-b-street/abstreet/files/10514344/output.txt)

I was trying to test issue #1051 on my local macbook.

This is the cause of the crash: 
'main' panicked at 'Couldn't find the ltn executable. Is it built?'

I am probably missing something simple, how can I build the low traffic neighbourhood executable?

**Comment by dabreegster** [comment]
`cd apps/ltn; cargo build --release`

On native, when you switch between different apps (split into different crates under the `apps/` directory), it checks a few possible places for this file: https://github.com/a-b-street/abstreet/blob/8f1ec9e563246b6d38c300f70379d9c2b1cd3ede/map_gui/src/tools/mod.rs#L353

**Comment by Transurgeon** [comment]
Oh ok, makes sense.

I didn't notice further crates under the apps directory.
