### ISSUE TITLE
The app crashed!

### ISSUE THREAD

**Issue by etam** [a-b-street/abstreet#1064]
I was following tutorial. After I changed parking lanes to bike lanes, this happened:

> panicked at 'PolyLine::make_polygons() failed: Ring has repeat non-adjacent points near Pt2D(709.1134, 719.801)', geom/src/polyline.rs:526:20

The url was `http://play.abstreet.org/0.3.39/abstreet.html?--cam=19.63%2F47.64048%2F-122.31122`

**Comment by dabreegster** [comment]
Thanks for reporting! Will look into this when there's time

**Comment by dabreegster** [comment]
Duplicate of #1078
