### ISSUE TITLE
LTN doesn't find all shortcuts (v0.3.43 windows)

### ISSUE THREAD

**Issue by rouelibre1** [a-b-street/abstreet#1092]
While using the tool I noticed that some shortcuts in my neighborhood are not detected. 

Editing OSM data on the road (adding explicitly "oneway=no") seems to fix the issue. (https://www.openstreetmap.org/way/239371917)

Does it mean that for every road without the "oneway" tag it will be interpreted as a blocked road for motor trafic ? And won't detect the shortcut ? I think I remember the tool interpreting the absence of "oneway" tag as a "no" value (but it was some time ago, so I can't be so sure)

Also, I'm using 0.3.43 because 0.3.44 doesn't launch when I try it.

**Comment by dabreegster** [comment]
Thanks for reporting this bug!

Explicitly adding `oneway=no` has no effect here. It's redundant on `highway=residential` and most other roads. If you want an easier way to check how A/B Street will interpret OSM tags, you can use https://a-b-street.github.io/osm2streets/lane_editor.html#16.34/48.569161/7.771363. If I remove `oneway=no` there and regenerate, there's no change. (If you notice something odd here, by the way, it might mean the logic for understanding tags is wrong, so I wouldn't necessarily edit OSM as the fix!)

I'm importing the area to check now, but could you please post a screenshot or similar and show what shortcut you'd expect to see, but don't?

> Also, I'm using 0.3.43 because 0.3.44 doesn't launch when I try it.

What's 0.3.44 do when you try to launch? If you have an `output.txt` file, what's it say?

**Comment by dabreegster** [comment]
Also if you haven't found the Shortcuts tool (F4), it's useful for understanding what shortcuts the tool thinks is currently possible. All it's doing is calculating the shortest path between every entrance and exit for the area you've selected.

https://github.com/a-b-street/abstreet/assets/1664407/5f400dbf-19dd-448e-9393-04111c956b87

**Comment by rouelibre1** [comment]
> What's 0.3.44 do when you try to launch? If you have an `output.txt` file, what's it say?
 
 I get an output file with the following text: 
 
 '.' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.

Which stand for:

'.' is not recognized as an internal or external command
or external command, an executable program or a command file.

This issue seems to occur with all ABstreet versions > 0.3.43 (I reproduced with 0.3.46 and 0.3.47 today)

Is there anything more that I can do to help diagnose the problem ?

**Comment by rouelibre1** [comment]
Hi ! I confirm successful launch of v0.3.48 on Windows :)
Thanks for fixing the issue.
Also, I can't reproduce my initial issue with "undetected shortcuts".
I believe this is a win !
