### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by deevroman** [a-b-street/abstreet#1097]
`Error Couldn't load montlake (in seattle (us)) invalid value: integer '256', expected variant index 0 <= i < 2`

<img width="339" alt="Снимок экрана 2023-08-14 в 11 43 23" src="https://github.com/a-b-street/abstreet/assets/25708359/88a0f2a2-f541-4efb-839e-fa879732ac5c">

Versions: 
1. Browser: Firefox 116 https://play.abstreet.org/0.3.46/abstreet.html
2. Built from source, macOS 13.5, M1 Chip

**Comment by dabreegster** [comment]
Thanks, the new release has a problem. The docs and links should update shortly, but please use https://play.abstreet.org/0.3.45/abstreet.html in the meantime

**Comment by dabreegster** [comment]
Sorry this took so long to fix :(   The 0.3.46 link should work fine now, and I've re-released https://github.com/a-b-street/abstreet/releases/tag/v0.3.46
