### ISSUE TITLE
Choppy scrolling of intro splash screen background

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#112]
When I open the game, there is a scrolling streetscape behind the AB Street logo. If my mouse is not on the "Play" button, the scrolling is choppy. If I mouse over the "Play" button (without clicking), the scrolling is perfectly smooth. As soon as the cursor is no longer hovering over the "Play" button, the scrolling is choppy again.

FWIW, I think this is a an issue with available CPU resources. The scrolling is choppy because some process is taking up a bunch of CPU resources when the cursor is not over the "Play" button. When my mouse is not over the "Play" button, all other programs on my computer are slow and choppy as well, in addition to the background map scrolling. It takes a few seconds to switch desktops and there is a half-second-ish lag between key presses and text appearing onscreen. Seems like some severe computer brainmelt is occurring (my computer is over 10 years old and has limited brains to melt, which doesn't help).

**Comment by dabreegster** [comment]
I've observed this before on a new machine, but I can't reliably reproduce. I made sure nothing weird like trying to recalculate mouseover uselessly is happening. Next time I spot this happening, I'll try to dig in. If I had to guess, probably the core ezgui runner loop is a little bit incorrect with how it handles events and decides when to redraw.

**Comment by dabreegster** [comment]
The scrolling intro screen has been gone for a bit
