### ISSUE TITLE
Trying to load Camden data to test low traffic neighbourhoods

### ISSUE THREAD

**Issue by JeanDollimore** [a-b-street/abstreet#1120]
Diagnostic

"panicked at called Option::unwarp() on a 'None 
' value, map-Model/src/apply.rs.419.56

**Comment by JeanDollimore** [comment]
Hi Dustin

That’s a very quick reply. It crashed o trying to load the Camden data.I wonder whether i was using an obsolete version of your software accessed from here: https://a-b-street.github.io/docs/software/ltn/index.html

I have just found another way in via

http://play.abstreet.org/0.3.15/abstreet.html?system/gb/london/maps/camden.bin&--cam=16.44/51.56406/-0.14316

which can load the Camden map. 

Actually the proposed LTN is on the Camden Islington border. It’s bounded by Highgate Road- West Hill, Highgate Hill, Junction Road and Fortess Road, Is there any way we could load the two together?


Jean

**Comment by dabreegster** [comment]
Hi Jean!

I've fixed the crash that you found, but it's not in a release or the web version yet.

The easiest way to get something cross-borough is to use the downloadable version and import the map yourself. Install from https://github.com/a-b-street/abstreet/releases, then do https://a-b-street.github.io/docs/user/new_city.html#the-easy-method. This GeoJSON boundary covers everything:

```{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[[[-0.16497358838319087,51.577700615376784],[-0.16497358838319087,51.548034858372404],[-0.12366324227289738,51.548034858372404],[-0.12366324227289738,51.577700615376784],[-0.16497358838319087,51.577700615376784]]],"type":"Polygon"}}]}```

I had to stretch the boundary to cover the area you said, but it was straightforward:
![Screenshot from 2023-09-29 17-25-23](https://github.com/a-b-street/abstreet/assets/1664407/406c0876-a9a4-4ff8-8aa7-77f520395d2c)

I tried a few bus gates to stop the north/south shortcuts, but it's definitely a tricky area! Do you have a link to the plans being proposed?

Let me know if you have trouble importing locally, and I can see about adding a map covering that area. It's not the most scalable solution on my end though, to keep adding more and more unusual boundaries. But necessary until the web version can easily import custom areas too.

**Comment by JeanDollimore** [comment]
Hi Justin,

Thank you for getting back to me.

You have managed to do exactly what I want! I hadn’t even been able to alter the boundary to the Camden part because it seemed to think that Chetwynd Road wasn’t allowed to be internal.

Camden Council are doing a Commonplace engagement here: https://dartmouthpark.commonplace.is/

They are working with islington to make an LTN over the area I described to you. It’s an interesting area with all sorts of issues e.g. Swains Lane where cyclists do hill climbs  has a cemetery requiring access part way up but it desperately needs to be filtered e.g. above the cemetery where the road is rather narrow for turning round. There are bus routes and bus gates will be needed. The major destination in the area is the Whittington Hospital but emergency services would be able to use the bus routes at least. 

I am thinking of a solution a bit like the centre of Groningen where there are four areas and if a car needs to go from one to the next it had to go round the outside. (whereas bikes can go straight through).

If necessary I will do what you say to get the area I need. But is there any chance you could just give me access to the work you’ve already done? as shown in your screen grab.

Best wishes 

Jean

**Comment by dabreegster** [comment]
Hi Jean, sorry for the delay! Give https://play.abstreet.org/0.3.48/ltn.html?system/gb/london/maps/highgate.bin a try -- it's a newly imported map that covers everything here. You can adjust the boundary as needed, or if you have trouble, try this proposal that I started: https://play.abstreet.org/0.3.48/ltn.html?system/gb/london/maps/highgate.bin&--proposal=remote/cfe8dc4b619eb2b3123fd3699a8a7c79

I don't have lots of time to work on this tool right now, but I'll think through some other approaches where I can import a new map (a quick process for me) without having to release a new build (slower).

Closing the issue for now, but please reopen if something's not working, or if you'd like to share any results. Thanks!

**Comment by JeanDollimore** [comment]
Hi Dustin

Thank you very much. That looks great and I do seem to have managed to get the boundary where I want it. 

I like the ability to draw the filters as it is more direct in terms of where they go. I also like the bus gates and other new details such as for one-way streets.

I will send you the ‘result’ if/when I manage to get there!

Jean
