### ISSUE TITLE
cant parse hebrew

### ISSUE THREAD

**Issue by idshklein** [a-b-street/abstreet#1128]
Hi, I played with the tel aviv net and the software crashed, this message was in the output file
[2023-11-24T08:46:41Z WARN  usvg_text_layout] No fonts with a ם/U+5DD character were found.

**Comment by idshklein** [comment]
I think this is the right font
https://fonts.google.com/noto/specimen/Noto+Sans+Hebrew

**Comment by dabreegster** [comment]
Thanks! I hope to have some time to catch up on A/B Street issues in the next few weeks

**Comment by dabreegster** [comment]
![Screenshot from 2023-11-26 19-16-09](https://github.com/a-b-street/abstreet/assets/1664407/40c58229-b08b-491d-b3f0-6899636d9205)
Road names are showing up now! If there's any rendering issues, let me know (though I'm near powerless to fix them -- relying on usvg and some other lower-level libraries for all the text rendering).

I'll keep looking into the geometry crash; that's an ongoing problem everywhere in this codebase

**Comment by dabreegster** [comment]
(There will be a new release at some point, but in the meantime, the LTN tool is up-to-date here: https://a-b-street.github.io/abstreet/web/ltn.html?system/il/tel_aviv/maps/center.bin)
