### ISSUE TITLE
Import a new map

### ISSUE THREAD

**Issue by ReyTapas** [a-b-street/abstreet#1145]
I have a problem to import map. I have this message : (see the attach file)
![Capture d'écran 2024-06-25 140535](https://github.com/a-b-street/abstreet/assets/173800063/4ae61098-7d51-4d7d-bc77-4e70744617af)

Do you have an idea how resolve problem ?

Thank you in advance

**Comment by michaelkirk** [comment]
I'm not really familiar with the import process, but the error message you provided looks cropped after `host: Some(Domain("overpass-api.de")), port: No`, 

Can you provide more of it? Or if you start the application from a terminal, there may be more useful output logged to the terminal.

**Comment by ReyTapas** [comment]
Hello,

You're right it was a proxy restriction, with cropped after host.
With a personnal connexion it works.

Thank you anyway

Quentin
________________________________
De : Michael Kirk ***@***.***>
Envoyé : mardi 25 juin 2024 20:09
À : a-b-street/abstreet ***@***.***>
Cc : CHAVET Quentin ***@***.***>; Author ***@***.***>
Objet : Re: [a-b-street/abstreet] Import a new map (Issue #1145)


I'm not really familiar with the import process, but the error message you provided looks cropped after host: Some(Domain("overpass-api.de")), port: No,

Can you provide more of it? Or if you start the application from a terminal, there may be more useful output logged to the terminal.

**Comment by dabreegster** [comment]
Thanks for helping Michael! Glad it's working
