### ISSUE TITLE
Location names in Cyrillic do not load

### ISSUE THREAD

**Issue by mrBluestSky** [a-b-street/abstreet#1147]
I've tried to load a few cities across Kazakhstan. The program's GUI does not show most street and amenity names. The locations here are generally named using the Kazakh version of the Cyrillic alphabet. When trying to load place names with a Cyrillic name, logs display output akin to this:

`[2024-08-11T13:26:45Z WARN  usvg_text_layout] No fonts with a е/U+435 character were found.`

Here is my output.txt file. 
[output.txt](https://github.com/user-attachments/files/16573835/output.txt).

I think that this issue can be easily solved by adding a fallback font. 

Is it OK if I create a pull request that adds support for automatic activation of a fallback font in case the default font cannot render a glyph? I will try to solve this issue if the core team is OK with that.

**Comment by dabreegster** [comment]
Hi! We have a way to configure fallback fonts per country code. If you can point me to one of the noto sans fonts (preferably), then I can add it in. The slightly harder part is that the font fallback currently uses country codes to figure out what to load, and for temporarily imported maps, the fake `zz` country code is used. As a really rough hack, we could make `zz` just load all the extra ones.

https://github.com/a-b-street/abstreet/blob/d30c36a22a87824d3581e0d0d4e2faf9788d6176/map_gui/src/load.rs#L33

Depending what part of A/B Street you're using, there might be a much simpler way -- development in this repo has stalled out, but the projects I'm working more actively on are web-first/only, using MapLibre GL, where fonts (and many other things) work much better. Some of the tools:

15-minute rewrite: <https://a-b-street.github.io/15m/#15.34/49.81413/73.097357>
LTN tool rewrite: https://a-b-street.github.io/ltn/#15.34/49.81413/73.097357
A new tool focused on walking / crossings: https://a-b-street.github.io/severance_snape/#15.34/49.81413/73.097357

**Comment by mrBluestSky** [comment]
The problem has been personally solved by using a dirty hack on the load.rs file.

off-topic comment:
These rewritten tools certainly work better! By the way, do you have any plans to fully rewrite this project to create a street-editing and simulating tool?

**Comment by dabreegster** [comment]
Glad the local fix worked :)  If you send GeoJSON boundaries, I can add some Kazakhstan cities to the built-in list, so the font fallback could be done for the future. But I'm not likely to roll a new build anytime soon, so if you're not trying to share with someone else, not much point.

> do you have any plans to fully rewrite this project to create a street-editing and simulating tool?

The street-editing part is likely to happen first. One of my work projects involves some best practice guidance (from UK design standards) around lane/street feature widths, and figuring out if a route with some cross-section would fit within physical constraints. I'm hoping to rethink the lane editor ideas in A/B Street for that. Traffic simulation, probably not anytime soon -- it's just massively complex and hard to get correct, and doesn't really seem that useful for decision-making anyway.
