### ISSUE TITLE
LTN tool - diagonal filter

### ISSUE THREAD

**Issue by skinofstars** [a-b-street/abstreet#1152]
Hi, 

I'm using the LTN tool and I want to put a diagonal filter across a four way junction. Is this possible?

Thanks,
Kevin

**Comment by dabreegster** [comment]
Yes! You just click the intersection itself. You might want to first change the filter icon to the "no entry" style, so you can actually see the direction of the diagonal:
![image](https://github.com/user-attachments/assets/0a50793f-d98c-456d-98b8-8b82cd116de6)
![image](https://github.com/user-attachments/assets/9588fc8b-70f9-405f-8873-3cfd14643d51)
If you're using the new version of the LTN tool by chance (https://a-b-street.github.io/ltn), then diagonal filters aren't added in yet, but it's on the  roadmap.

**Comment by dabreegster** [comment]
That's the original version, it has diagonal filters. Change the filter icon near the bottom to the "no entry" one, then try clicking a four-way intersection

**Comment by skinofstars** [comment]
Great, thanks
