### ISSUE TITLE
Potential fix to very slow performance

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#125]
This is partly a bug report, partly a user enhancement.

On my super slow, old laptop, simulations can run very slowly (1-to-1 real time to simulation time or worse, even on 3600x acceleration) on a large map like South Seattle with many active trips (especially once gridlock sets in). I have found that I can very dramatically improve the simulation speed if I zoom the view out enough to switch from detailed lane-specific view to the lower-resolution view where all travelers are represented by dots of different colors. To get the fastest performance, I zoom the map out just far enough to switch views but no farther and then uncheck all forms of travelers from the display. For me, this trick makes the difference between taking the simulation from midnight to 6 a.m. in several minutes versus several hours.

Now, the recommendation. 1) Let users know about this option via the tutorials or some other help resource, if it's not already in there. 2) Make a one-click "turbo time warp" mode that minimizes graphic processing to get the fastest-possible simulation on machines with limited resources. I can imagine that this could be a global option, i.e. a radio button in a settings menu selecting either "Pretty timewarps" or "Utilitarian timewaps".

**Comment by dabreegster** [comment]
Added a checkbox on the jump-to-time panel for the 2nd idea. Is this usually how you advance large steps? I could also expose it in the settings panel.

**Comment by belt-drive** [comment]
I hadn't been using the jump-to-time panel, but now that you mention it,
it's an easier method than what I've been using. I was using the button at
the bottom of the screen to continuously jump +1 hour and then had the game
speed set to 3600x to keep things moving fast when it drops from time warp
back into the regular game mode. The jump-to-time window is a much easier
way to achieve the same effect.

**Comment by dabreegster** [comment]
That's very useful UX feedback. :D  Is there any reason why the jump control wasn't an obvious match? We've pondered variations of combining the time/speed panels before that could make jumping to a time easier, but so far not implemented them. On larger maps and slower computers, jumping back/forth through time is inevitably slow, so hiding the control behind a button seems justified.

**Comment by belt-drive** [comment]
I think the jump control wasn't an obvious match because I didn't see it
(or remember it) until you reminded me about it. It was probably included
in the tutorial, but I clearly didn't remember it. There is a lot going on
in the game, and it can be pretty overwhelming at first. It would probably
be good to retake the tutorial again after spending some time with the game
to remind me of things that I've missed. It's likely that there are other
ways that I'm not optimizing my use of the interface.
