### ISSUE TITLE
Handle highway on/off ramp geometry better

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#131]
As an example, see screenshot below of E Marginal Way and Boeing Access Rd in south Seattle. With some many intersections packed close together, it can be hard to tell what's going on with any individual intersection and why paths might be blocked. There are some crosswalks that are hard to decipher, like the one going diagonally halfway across E Marginal. It seems like this is more often an issue with on-/off-ramps and short access roads that create a bunch of tiny sometimes-overlapping intersections.

I was thinking about a potential "intersection amalgamator" that bundles intersections that are within x distance. Or, maybe it's just easier to treat these issues by hand since there are relatively few of the really serious ones where you start getting crazy crosswalks.

(FWIW, Boeing Access Rd is a total cluster in real life, so not surprising that the game has trouble with it, too)
<img width="1280" alt="Screen Shot 2020-07-04 at 6 28 10 PM" src="https://user-images.githubusercontent.com/67647924/86545537-713f0d80-bee4-11ea-827c-31b0fe3687b5.png">

**Comment by dabreegster** [comment]
Sidewalks and crosswalks are a particularly tough thing in OSM. There's an way to tag where they are explicitly, but the coverage in Seattle is very bad, and there's no way to distinguish "there's legitimately no sidewalks here" from "this area hasn't had sidewalks mapped yet". So for the moment, I'm making [very rough guesses](https://github.com/dabreegster/abstreet/blob/3f912e220c5ea66d77b769935dcd79599552b34f/convert_osm/src/osm_reader.rs#L389). There are potentially other data sources like https://data-seattlecitygis.opendata.arcgis.com/datasets/sidewalks/data, but snapping this to OSM roads is nontrivial.

The algorithm that generates crosswalks between the inferred sidewalks is [even worse](https://github.com/dabreegster/abstreet/blob/3f912e220c5ea66d77b769935dcd79599552b34f/map_model/src/make/turns.rs#L297). I haven't touched this in a long time; I'll take some time this week to revisit it with fresh assumptions.

**Comment by matkoniecz** [comment]
> but the coverage in Seattle is very bad

If you are local resident with an Android phone then StreetComplete app may be useful! It asks about some missing data, including question about presence of sidewalks (in settings you may reorder quests, so you can push sidewalk one to the top).

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-06 20-14-06](https://user-images.githubusercontent.com/1664407/86699654-411b6b80-bfc5-11ea-9c58-c34963fd111d.png)
I tagged some of the sidewalks (and lack thereof) today, and this area is looking a little better.

I think the other main issue is how A/B Street fails to handle highway on/off ramps. A simple example is here:
![Screenshot from 2020-07-06 20-15-11](https://user-images.githubusercontent.com/1664407/86699858-6e681980-bfc5-11ea-8411-5578bff172a3.png)
Check out https://www.openstreetmap.org/way/431103954. I've found https://wiki.openstreetmap.org/wiki/Proposed_features/placement, which isn't an accepted OSM schema, but it explains the problem clearly. I'll think about adjustments to the intersection polygon algorithm.

**Comment by matkoniecz** [comment]
> which isn't an accepted OSM schema

Note https://wiki.openstreetmap.org/wiki/Any_tags_you_like - going through a proposal vote is completely optional

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-11 16-30-01](https://user-images.githubusercontent.com/1664407/87235721-cf139f80-c393-11ea-8d9e-605fce68ca14.png)

I finished tagging lack of sidewalks in this area, and corrected the number of lanes on Marginal. It was 6, probably from before the road was split into a divided highway. The area almost looks reasonable now. If it's OK, I'm going to repurpose this bug to track the work to make better geometry for on/off ramps, since that's causing most of the remaining issues here.

**Comment by belt-drive** [comment]
Sounds good to me! Thanks for the work, and repurpose away.

**Comment by dabreegster** [comment]
![Screenshot from 2020-08-04 15-46-18](https://user-images.githubusercontent.com/1664407/89352777-d31c9f80-d669-11ea-97c3-a136b51d52af.png)
Highway geometry is really strange. I think the ideal intersection polygon here is in red. The southern piece actually needs to be lengthened by the green line's length. Trying this.

**Comment by dabreegster** [comment]
Before:
![Screenshot from 2020-08-04 16-54-19](https://user-images.githubusercontent.com/1664407/89356673-3e1ea400-d673-11ea-8bfa-c140c19ed52c.png)

After:
![Screenshot from 2020-08-04 16-54-36](https://user-images.githubusercontent.com/1664407/89356680-41b22b00-d673-11ea-87ff-06e6723c1c88.png)

Besides just looking much more like a proper highway exit lane, the smaller intersections mean that turns take much less time to cross. So vehicles spend less time contending for a critical resource.

**Comment by dabreegster** [comment]
Progress!
![Screenshot from 2020-08-05 10-24-29](https://user-images.githubusercontent.com/1664407/89443958-debda400-d705-11ea-9c65-b3a47a8f539a.png)
![Screenshot from 2020-08-05 10-24-16](https://user-images.githubusercontent.com/1664407/89443965-dfeed100-d705-11ea-81c7-49fd6f7e49bf.png)

**Comment by dabreegster** [comment]
Making progress with fixing geometry generally in #654, not useful to keep this issue open too
