### ISSUE TITLE
bicycle=use_sidepath indicates cycleway along road

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#169]
Note that representing `highway=cycleway` and `highway=path bicycle=designated segregated=yes` as roads with solely bicycle lanes would be strictly superior. 

If that is unfeasible then solution below is a hacky partial workaround that would help map of Kraków a bit.

----

Proper support for detached cycleways would be nice, it is not really indicating what side has cycleway but may be better than nothing

https://taginfo.openstreetmap.org/tags/bicycle=use_sidepath - 125k uses

bicycle=use_sidepath - may be reduced to cycleway=lane (possibly wrong as it is possible that only one side had cycleway, lane vs separate cycleway is not an exact match)

bicycle:forward=use_sidepath - may be reduced to bidirectional cycleway on the driving side (forward lane for all vehicles, backward for bicycles, forward lane for bicycles - but it was mentioned as not representable) https://taginfo.openstreetmap.org/tags/bicycle%3Aforward=use_sidepath

bicycle:backward=use_sidepath - may be reduced to bidirectional cycleway on the side opposite to the driving side (backward lane for cyclists, forward for cyclists, forward lane for all vehicles - but it was mentioned as not representable) https://taginfo.openstreetmap.org/tags/bicycle%3Aforward=use_sidepath

**Comment by dabreegster** [comment]
I think now that we're bringing in all separate cyclepaths, we don't need to look at this tag. Please reopen if I'm wrong.

(I'll grab fresh Krakow OSM, so if you audit for missing bike paths, everything should be up-to-date.)
