### ISSUE TITLE
Concave hull implementation

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#198]
For anybody algorithms focused, I'd love a concave hull implementation in Rust. It would allow better shapes around clusters of buildings, used to visualize patterns over many trips.

![Screenshot from 2020-07-14 17-52-13](https://user-images.githubusercontent.com/1664407/87490553-d5578500-c5fa-11ea-883a-e7b055bf6842.png)

https://adared.ch/concaveman-cpp-a-very-fast-2d-concave-hull-maybe-even-faster-with-c-and-python/
https://towardsdatascience.com/the-concave-hull-c649795c0f0f
https://github.com/joaofig/uk-accidents/blob/master/geomath/hulls.py

**Comment by dabreegster** [comment]
https://github.com/AndriiHeonia/hull/blob/master/src/hull.js
https://github.com/sebastianbeyer/concavehull/blob/master/ConcaveHull.py
https://github.com/jsmolka/hull/blob/master/hull.py
https://github.com/Merowech/java-concave-hull/blob/master/ConcaveHull.java

**Comment by dabreegster** [comment]
Thanks @RestitutorOrbis! https://github.com/dabreegster/abstreet/tree/use_concave_hull switches over to this. The effects are quite nice, "shrinkwrapped" around just the purple buildings. With concavity of 0.1:
![concave_0 1](https://user-images.githubusercontent.com/1664407/97039553-7b335d80-1521-11eb-831b-2f72c70cd745.png)

But for some of the cases, the algorithm seems to give up one corner and just cut across. I tried concavity as low as 0.01 here, but it happens for 1.0 and 2.0 as well:
![concave_0 01](https://user-images.githubusercontent.com/1664407/97039696-ab7afc00-1521-11eb-8711-ea4ab66e52f8.png)

Any tips on tuning that parameter? I found this from concaveman: "concavity is a relative measure of concavity. 1 results in a relatively detailed shape, Infinity results in a convex hull. You can use values lower than 1, but they can produce pretty crazy shapes."

**Comment by RestitutorOrbis** [comment]
Hmm, that's concerning. Is it possible to get a dump of the inputs to the concave hull algo in that instance?

**Comment by dabreegster** [comment]
[concave_input.json.txt](https://github.com/dabreegster/abstreet/files/5432149/concave_input.json.txt)
I'll double check that only the expected building polygons are being fed in, but I really don't see along that diagonal in the park that'd be causing the concave hull to jut out so much...

**Comment by RestitutorOrbis** [comment]
@dabreegster You're right. I've opened a PR to address this here: https://github.com/georust/geo/pull/541.

**Comment by dabreegster** [comment]
Using new blockfinding now instead of concave hull generally
