### ISSUE TITLE
"Can't create an OpenGL window" on Ubuntu in Virtualbox

### ISSUE THREAD

**Issue by Blazar221** [a-b-street/abstreet#199]
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'Can't create an OpenGL window. Please file an issue at https://github.com/dabreegster/abstreet/issues/ and include output.txt. First attempt Received multiple errors. Errors: `[NoAvailablePixelFormat, NoAvailablePixelFormat]`, second attempt Received multiple errors. Errors: `[NoAvailablePixelFormat, OsError("Couldn\'t find any available vsync extension")]`, third attempt Received multiple errors. Errors: `[NoAvailablePixelFormat, OsError("Couldn\'t find any available vsync extension")]`', ezgui/src/backend_glium.rs:57:21
stack backtrace:
   0:     0x55a847222cf5 - backtrace::backtrace::libunwind::trace::h34afbfad7fd770fc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55a847222cf5 - backtrace::backtrace::trace_unsynchronized::h460d522b1619a600
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55a847222cf5 - std::sys_common::backtrace::_print_fmt::ha45fac10086813b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55a847222cf5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde84f63fcfd0e6de
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55a84724f6fc - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55a84721c452 - std::io::Write::write_fmt::hc344eafd6e850b4d
                               at src/libstd/io/mod.rs:1537
   6:     0x55a8472253d0 - std::sys_common::backtrace::_print::h4db88ff15cb5d61d
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55a8472253d0 - std::sys_common::backtrace::print::h5fc39e1b1f610bd3
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a8472253d0 - std::panicking::default_hook::{{closure}}::h59e55edacb1d974a
                               at src/libstd/panicking.rs:198
   9:     0x55a84722511c - std::panicking::default_hook::heee4c8016dfbf328
                               at src/libstd/panicking.rs:217
  10:     0x55a847225a13 - std::panicking::rust_panic_with_hook::h8405b6301c79fb5a
                               at src/libstd/panicking.rs:526
  11:     0x55a84722560b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x55a84722557b - std::panicking::begin_panic_fmt::h0ed87aa3b2c392e6
                               at src/libstd/panicking.rs:391
  13:     0x55a846d2edc6 - ezgui::backend_glium::setup::haf94aa498089623d
                               at ezgui/src/backend_glium.rs:57
  14:     0x55a8454dbd84 - ezgui::runner::run::ha175fe1d08846544
                               at /home/yrz/桌面/abstreet/ezgui/src/runner.rs:207
  15:     0x55a8456f56f1 - game::main::hbb00b1cec87ec719
                               at game/src/main.rs:114
  16:     0x55a84586e12b - std::rt::lang_start::{{closure}}::hf9a72a5a8601e925
                               at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/rt.rs:67
  17:     0x55a847225eb3 - std::rt::lang_start_internal::{{closure}}::h7cea099ad4edf1eb
                               at src/libstd/rt.rs:52
  18:     0x55a847225eb3 - std::panicking::try::do_call::h42d93372c44025d2
                               at src/libstd/panicking.rs:348
  19:     0x55a847225eb3 - std::panicking::try::hb47a4182362d3341
                               at src/libstd/panicking.rs:325
  20:     0x55a847225eb3 - std::panic::catch_unwind::h2afcfbf3125915b4
                               at src/libstd/panic.rs:394
  21:     0x55a847225eb3 - std::rt::lang_start_internal::h4f696727fe904f48
                               at src/libstd/rt.rs:51
  22:     0x55a84586e107 - std::rt::lang_start::hb29727741ba1ca2b
                               at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/rt.rs:67
  23:     0x55a8456f627a - main
  24:     0x7f34ec7180b3 - __libc_start_main
  25:     0x55a8453c02ee - _start
  26:                0x0 - <unknown>

**Comment by Blazar221** [comment]
I only have a windows system on my computer and use virtualbox because I need to run abstreet on linux later. Now abstreet can successfully run on my windows system, but I don't know how to disable vsync on linux system. Anyway, thanks for your immediate reply.

**Comment by dabreegster** [comment]
https://github.com/a-b-street/abstreet/blob/5f3c914e28f7e51eeacd4edc5119cf0ad1366d14/widgetry/src/backend_glow_native.rs#L22
We've since added a bunch of OpenGL context fallbacks, so this might be working now, even in virtualbox. Please reopen if not.
