### ISSUE TITLE
unclear reason for warning - starting at #0 (null?) interesection

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#205]
```
Route https://www.openstreetmap.org/relation/2001911 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
Route https://www.openstreetmap.org/relation/8117382 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
Route https://www.openstreetmap.org/relation/3154709 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
Route https://www.openstreetmap.org/relation/10534635 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
Route https://www.openstreetmap.org/relation/10535270 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
Route https://www.openstreetmap.org/relation/3554767 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
Route https://www.openstreetmap.org/relation/10541263 starts at Intersection #0 (OriginalIntersection(https://www.openstreetmap.org/node/-13)), but no starting lane for a Bus?
```
Why it starts at #0 intersection? Why it complains about missing lane for bus?

https://www.openstreetmap.org/relation/2001911#map=19/50.06763/19.94667&layers=N
![screen03](https://user-images.githubusercontent.com/899988/87869988-6a180500-c9a4-11ea-92ab-3181ca623b5a.png)

Also, original intersection reports modified geometry created by AB, not actual OSM node.

**Comment by dabreegster** [comment]
Negative OSM IDs come from clipped roads near the map boundary, created by `convert_osm/src/clip.rs`. What happens with clipping is kind of weird. If a road goes straight out the border, then the border intersection is just snapped to the boundary, and it retains the original OSM node ID. But if the road goes out the border, then back in, or if that intersection just outside the boundary is connected to a second road that also crosses the boundary, then it splits the boundary intersection into two, and makes up a new negative OSM node ID. I tried avoiding this, but if you leave that intersection in, you wind up with a border intersection connected to two roads. That might be OK to model, but we'd have to think through the implications -- an agent could make a normal turn there at remain in the map, or leave the map. Kind of odd.

Turn restrictions get entirely messed up by clipping. I'll look into what's happening here.

**Comment by matkoniecz** [comment]
In this case I think that ways involved should not be touching map edge.

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-19 13-48-47](https://user-images.githubusercontent.com/1664407/87884930-96447d80-c9c6-11ea-9734-00439af76382.png)
Intersection 0 is indeed a border. Your screenshot shows i1544, how'd you get there from the logs? (In dev mode by the way, you can do **ctrl+j** and then warp to **i123** to jump to an intersection by ID (not OSM node ID, the "intersection #123" one).

The problem with this route is that https://github.com/dabreegster/abstreet/blob/a837c79500a759546c78f3c36e7fbfef6d62a5b6/convert_osm/src/clip.rs#L193 incorrectly picked this intersection as the closest one to the first stop. I'll try making this matching insist on incoming/outgoing roads for starts/ends.

**Comment by matkoniecz** [comment]
> Your screenshot shows i1544, how'd you get there from the logs? 

Not from logs, I looked at relation id and assumed that it will start where it was mapped as starting. I guess that bus needs to actually roll onto map[0], so real starting point was elsewhere.

[0] at least for the first time - though I expect that for now it will leave map and enter it again rather than  finish trip in one direction and start trip in an opposite direction

> In dev mode by the way, you can do ctrl+j and then warp to i123 to jump to an intersection by ID (not OSM node ID, the "intersection #123" one

Thanks, I planned to look for something like that to locate all this places mentioned in logs!

**Comment by dabreegster** [comment]
Bus route importing is broken for many reasons, including this one, and is likely to change radically once it's picked up again. So closing this bug for now.
