### ISSUE TITLE
Support for traffic data by OpenDataCam

### ISSUE THREAD

**Issue by jvolker** [a-b-street/abstreet#228]
https://github.com/opendatacam/opendatacam

> OpenDataCam is an open source tool to quantify the world. It quantifies and tracks moving objects with live video analysis. It is designed to be an accessible, affordable and open-source solution to better understand interactions in urban environments.

> this entire setup is priced around $150. All software is based on open source components and runs completely locally. The software features a friendly user interface and is currently optimised for detecting and counting traffic participants

A group at CityLAB Berlin is currently evaluating this system for traffic analysis. Could this help to provide realistic traffic data when focussing on one particular crossing within A/B street?

What would be necessary to import and use the data of the camera within A/B street?
Counter history API: https://opendatacam.github.io/opendatacam/apidoc/#api-Recording-Counter_history_(CSV)

Thanks.

**Comment by dabreegster** [comment]
I can think of two possible uses.

1) Validating a traffic model. If we come up with a travel demand model, we could run the simulation and then use the throughput tool on a lane or intersection and see how many different agents pass through at some time. You could then take the same measurements in real life and compare counts. I don't know how to make use of the results. If they match, is it a sign to trust the simulation? If they don't, what action could we take to improve it?

2) Generating trip demand input. If you have counts around many areas, I could imagine some kind of graph-based algorithm that tries to figure out exact trip start and end-points that roughly match the measured counts along different roads. I don't have any knowledge of this algorithm (beyond a vague memory of somebody talking about this approach), and I'm not promising I could implement it, or that the results would be at all realistic.

**Comment by dabreegster** [comment]
Just cleaning up old issues. I'm still not sure how to make use of this kind of data. We're still barely touching the problem of generating travel demand, except for #424. If you have any ideas how to incorporate it, please reopen.
