### ISSUE TITLE
some crossings have broken self-crossing geometries

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#243]
I misremembered, it is less than 1% - not 5% to 10% like I claimed. All from Kraków import.

![screen01](https://user-images.githubusercontent.com/899988/88454248-7271b380-ce6e-11ea-9f53-1d3c12ac4773.png)
![screen02](https://user-images.githubusercontent.com/899988/88454249-73a2e080-ce6e-11ea-9c2c-487285d5bc6a.png)
![screen03](https://user-images.githubusercontent.com/899988/88454250-743b7700-ce6e-11ea-8898-ede575594d84.png)

**Comment by dabreegster** [comment]
![Screenshot from 2020-08-14 12-28-43](https://user-images.githubusercontent.com/1664407/90285986-bdf1fe80-de29-11ea-823b-b2fdc80f9f9d.png)
i1205 in lakeslice is another example

**Comment by dabreegster** [comment]
I'm cleaning up old issues. I'm very aware of all the geometry problems. #654 has notes about recent work
