### ISSUE TITLE
Consider tagging "intersection" ways in OSM

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#255]
https://www.openstreetmap.org/way/40416113 is one example of many. This is not a road, it's part of a complex intersection. It would be immensely helpful in A/B Street to reliably detect cases like this, to improve rendering, possibly auto-merge intersections, and deal with gridlock. Not sure if there should be a new schema, or something like https://wiki.openstreetmap.org/wiki/Key:area:highway or one of the other street area proposals could be used.

**Comment by matkoniecz** [comment]
Proposal for doing this was recently floated on mailing lists, I may try finding it.

**Comment by matkoniecz** [comment]
Is it maybe possible to automatically detect very short stretches of road between road sections with the same name?

Let me know if searching for mailing list posting would be useful.

**Comment by dabreegster** [comment]
I don't keep up with the mailing lists much, but I should probably start. Was it likely https://lists.openstreetmap.org/listinfo/tagging?

Detection is possible, but always has false positives and negatives. The best way forward IMO is to decide how to tag this, use auto-detection to highlight untagged candidates, then manually review and tag them. I'll probably take this route for #230 
![Screenshot from 2020-07-30 13-00-08](https://user-images.githubusercontent.com/1664407/88968763-ab41cc00-d264-11ea-9cc2-654b93ef798c.png)

**Comment by dabreegster** [comment]
https://lists.openstreetmap.org/pipermail/tagging/2020-July/053786.html

**Comment by matkoniecz** [comment]
Recommendation: in case of subscribing to tagging use a separate account (digests are in theory alternative, but it makes responding nearly impossible)

**Comment by dabreegster** [comment]
#654 is now detecting some cases of these automatically
