### ISSUE TITLE
Intermediate/advanced projects

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#266]
Backlog of larger efforts that feel imminently important. Not appropriate for small starter bugs, but maybe more inspiring for longer-term work.

- Robustify the map importer, get MANY cities working
  - Easy source: https://download.bbbike.org/osm/bbbike/
  - Most places hit geometry problems, especially overlapping segments. Manually fixing is ideal, but tedious. Maybe in the meantime, totally cut out broken areas and warn very loudly?
  - Start to brainstorm infrastructure for regularly maintaining many cities, allowing players to opt-into downloading more maps
- Driving on the left side of the road
  - Preliminary support exists, but is buggy
  - This also affects lane-changing heuristics, turn creation, traffic signal heuristics (assuming right-turn-on-red)
- Better representation of public transit platforms/stations
  - Right now, the pedestrian position is just snapped to the nearest sidewalk or shoulder. No way to describe the few minutes it takes to navigate a larger underground station.
- Auto-tuning traffic signals
  - One of the biggest gridlock sources
  - Either statically use the scenario, calculate all the paths that happen each hour, then compute the best traffic signal policy to handle that demand
  - Or do it live, maybe adjusting the policy in real-time
  - Add support for signal "plans" -- the configuration changes for morning rush hour, late at night, etc. Relatively easy to code up in the map model, but possibly hard to represent in the UI.
- Prep for web/WASM support
  - The current hack statically bundles binary map/scenario data into the wasm file. Probably better to send XmlHttpRpc requests and actually download it. Might require some interesting rearchitecting for async

**Comment by khuston** [comment]
Hello, I'm interested in looking at "auto-tuning traffic signals".

I would like to support simulation of actuated traffic signals. I think a lot of behavior could be captured by including [features found here](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter5.htm) like (1) skipping phases that aren't called, (2) making artificial calls to "recall" preferred phases every cycle, (3) specifying parameters like minimum green interval, maximum green interval, passage time gap before terminating a phase.

If implementing actuated traffic signals with the parameters listed above sounds good, I can move ahead with it.

Without having gotten my hands dirty yet, I just have a couple other thoughts:

1. In real life, I assume that actuated left turns are only possible when left-only turn lanes are present. (Then again, I suppose the technology exists to identify when cars are waiting for a left turn.) For now I'll just ignore this and look at what turns are requested?

2. I am not planning to touch phase generation or phase sequencing in this first piece of work. The only change to phase sequence will be the opportunity to skip a phase while running if it has not been called.

3. Multi-signal coordination with actuated signals will require a bit more thought - I need to look into how they maintain a synchronized cycle.

Later, as a separate task, I could look into optimizing phase durations for pre-timed signals and optimizing maximum green intervals and preferred phase for actuated signals.

**Comment by dabreegster** [comment]
I'm cleaning up this old issue, since everything has either been done (!!!) or has its own more specific issue (like public transit)
