### ISSUE TITLE
Oversized GUI, no option to change this

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#381]
On a laptop with a large resolution GUI elements seem unreasonably large with no option to change this.

Curiously, nearly all software on Linux has rather unreasonably small GUIs (so scaling to size of a bottom bar would be going too far in the other direction).
![screen06](https://user-images.githubusercontent.com/899988/98114543-afa20480-1ea5-11eb-99e7-2c827cc96b3a.jpg)

**Comment by dabreegster** [comment]
Woops, sorry for not letting you know about `--scale_factor` earlier.

> Curiously, nearly all software on Linux has rather unreasonably small GUIs

Your laptop probably has a HiDPI / Retina display. Look for some sort of display settings and check the scale. On Ubuntu:

![Screenshot from 2020-12-07 14-54-45](https://user-images.githubusercontent.com/1664407/101551225-90473d00-3965-11eb-9ae7-8a2d96363803.png)

**Comment by matkoniecz** [comment]
> Look for some sort of display settings and check the scale. On Ubuntu:

Sadly, it seems that Lubuntu completely fails here ( at least according to https://askubuntu.com/questions/1298632/adapt-lubuntu-20-04-to-hdpi-screen ), it may be time to switch OS for the third time (as Lubuntu abandoned focus on performance that caused me to select it).

**Comment by dabreegster** [comment]
I think I just fixed this "once and for all" in #521. If you still have the laptop and get a chance, please try building from source or give the web version (http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--dev) a quick try.
