### ISSUE TITLE
On selecting car to enter the crossing give preference to cars not changing lanes

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#384]
For example crossing shown in https://github.com/dabreegster/abstreet/issues/382#issue-736103575 it would remove big part of absurdity with cars going from left to the right lane, while car on the right lane waits

**Comment by dabreegster** [comment]
Lane choice is still weird sometimes, but we have some other bugs for that, and this particular problem has been improved by Michael and Bruce's work on uber-turns
