### ISSUE TITLE
Unplayable - everything is huge sized

### ISSUE THREAD

**Issue by nekromoff** [a-b-street/abstreet#415]
![image](https://user-images.githubusercontent.com/8550349/101414552-964a0900-38e6-11eb-85ae-4b355fc5d9d7.png)

Ubuntu 20.04

**Comment by nekromoff** [comment]
possibly a duplicate of https://github.com/dabreegster/abstreet/issues/381
however that does not include similar buggy screenshot.

**Comment by nekromoff** [comment]
This seems to be incorrect. (why is *guessing* applied anyway?)
```
[INFO] winit::platform_impl::platform::x11::window: Guessed window scale factor: 3.1666666666666665
[DEBUG] winit::platform_impl::platform::x11::window: Calculated physical dimensions: 800x600
[INFO] widgetry::backend_glow: img_size: 896x896px (802816 px), sprite_size: 64x64px, sprites: 14x14 (196 sprites)
```

**Comment by michaelkirk** [comment]
Can you provide any more detail about your setup - are you running on multiple screens? Or a laptop with an external monitor?

**Comment by dabreegster** [comment]
Wow, I've never seen DPI above 2. Can you open the display settings in Ubuntu (you can just search for "Displays" in the Ubuntu app search tool) and let me know what "Scale" is?

![Screenshot from 2020-12-07 14-54-45](https://user-images.githubusercontent.com/1664407/101415115-32025780-389c-11eb-9fd6-54cdd2d52c49.png)

You can run with `--scale_factor=1` to force this to not happen. Could you please try that and include a screenshot? Are the controls and text too small for your monitor in that case?

**Comment by nekromoff** [comment]
xrandr output (external monitor enabled):
```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP connected (normal left inverted right x axis y axis)
1920x1080     60.01 +
1680x1050     60.01  
1280x1024     60.01
1440x900      60.01
1280x800      60.01
1280x720      60.01
1024x768      60.01
800x600       60.01
640x480       60.01
HDMI-A-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
1920x1080     60.00*+  50.00    59.94
1600x1200     60.00
1680x1050     59.88
1280x1024     60.02
1440x900      59.90
1280x960      60.00
1280x800      59.91
1280x720      60.00    50.00    59.94
1024x768      60.00
800x600       60.32    56.25
720x576       50.00
720x480       60.00    59.94
640x480       60.00    59.94
```

Distro is actually KDE Neon 20.04, based on Ubuntu.

Running with `--scale_factor=1` launches the software correctly.

**Comment by dabreegster** [comment]
Going back to the original log you posted:

> Calculated physical dimensions: 800x600

X11 tends to create windows of a fixed size, then immediately resize them to whatever was requested. I'm guessing the log later showed the correct resolution, so this is benign.

As for why the scale was incorrectly inferred, this must be a bug in https://github.com/rust-windowing/winit. I don't spot an open issue matching this problem, and I'm not sure what the next steps for debugging would be.

I'll add a note to the instructions to call out `--scale_factor`, at least.

**Comment by michaelkirk** [comment]
One thing which might help debug - you mentioned "external monitor", making me think you have another display - (your laptop?)

Could you try dragging the window to the other display and seeing if things look reasonable when launching the default app (*without* specifying --scale_factor).

I'm wondering if we're getting confused about the scale factor per display.

And if you're feeling really heroic, it'd be interesting if this problem reproduce when using the Wayland backend. (maybe something like this: https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-20-04-desktop) Though I'm not sure if  Neon supports that.

**Comment by nekromoff** [comment]
I have a unified display, but if I have laptop lid opened, the scale factor
changes to something more playable (although still bigger than 100%):
```
[INFO] winit::platform_impl::platform::x11::window: Guessed window scale
factor: 1.6666666666666667
[DEBUG] winit::platform_impl::platform::x11::window: Calculated physical
dimensions: 800x600
[INFO] widgetry::backend_glow: img_size: 896x896px (802816 px),
sprite_size: 64x64px, sprites: 14x14 (196 sprites)
```

Once I close the lid and use solely an external monitor, then the huge
sized interface bug occurs.

Wayland is supported here, although I don't use it. I'll try to login using
Wayland and report back.

**Comment by dabreegster** [comment]
I believe #521 should have fixed this. Even if the scale factor is detected improperly or gets confused by two screens, it'll be forced to 1 if the factor would wind up with a window that doesn't meet a minimum width.
