### ISSUE TITLE
Case study: maximum cycle length

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#446]
https://seattlegreenways.org/blog/2020/12/16/sdot-says-your-time-doesnt-matter-unless-you-drive/

There's a new signal policy that'll specify the cycle length at intersections in different zones (downtown, urban villages, industrial, etc). The policy fails to meet NACTO standards for limiting how long pedestrians should have to wait to cross. There's an opportunity to use A/B Street to do an analysis about the impact this could have on people walking around certain areas. In a worst case, under the new policy, a walking trip might take much longer.

- [x] Pick an area to study and make a smaller map. Likely Colombia City or Rainier Beach
- [x] Improve the existing heuristics for fixed signals, applying a configurable max cycle length and better guesses for how long major/minor roads get
- [x] Run the existing simulation with Soundcast data, using the worst-case timings and the NACTO recommendations
- [ ] Look at aggregate stats on how walking trips are affected
- [ ] Pick a few example trips that're impacted very badly, and video an A/B test showing the same person walking in two different worlds
- [ ] Figure out how to embed a stripped-down version of A/B Street in a blog post -- one that loads faster, doesn't include a full edit mode, omits challenges and title screens and such, and starts with the right scenario loaded

**Comment by dabreegster** [comment]
https://www.seattlebikeblog.com/2020/12/17/proposed-signal-policy-could-mean-more-long-waits-to-cross-streets/ has more detail

**Comment by dabreegster** [comment]
I got the full weekday scenario to run on this map! So now it's straightforward to measure how proposed edits affect things. I found just 3 traffic signals along Rainier Ave between the senior city and library -- at S Othello, Cloverdale, and S Henderson. At those 3, I applied the 96s/24s timing using a new convenience tool:
![Screenshot from 2021-01-26 18-29-21](https://user-images.githubusercontent.com/1664407/105934123-6d034a80-6004-11eb-949b-9f6ba3b2d8a7.png)

How'd these changes work out? Keep in mind that the signals before had a cycle length of 60s, evenly split -- which is an unrealistic baseline. Overall results:
![Screenshot from 2021-01-26 18-30-37](https://user-images.githubusercontent.com/1664407/105934212-9ae88f00-6004-11eb-84ef-e16e1acfce2c.png)
Just walking:
![Screenshot from 2021-01-26 18-31-10](https://user-images.githubusercontent.com/1664407/105934249-adfb5f00-6004-11eb-8d62-5235aedd3444.png)
Can look for individual walking trips that got much slower:
![Screenshot from 2021-01-26 18-32-32](https://user-images.githubusercontent.com/1664407/105934366-e307b180-6004-11eb-84a9-9e01ac6ea767.png)

**Comment by michaelkirk** [comment]
Great to see things starting to take shape.

I'm curious what's going on with that highlighted trip where walking could be 13% slower while only waiting 7s total.

**Comment by dabreegster** [comment]
Luckily it's easy to debug these things. It was the previous trip taking too long:
![Screenshot from 2021-01-27 11-17-45](https://user-images.githubusercontent.com/1664407/106041993-5b1bb900-6091-11eb-8139-b2c0d24c57e7.png)
Although this is honestly a case where the Soundcast data looks funky. Trip 1 starts at 5:43pm and has to go this far:
![Screenshot from 2021-01-27 11-17-45](https://user-images.githubusercontent.com/1664407/106042082-72f33d00-6091-11eb-8a4d-983b95873c9e.png)
Before leaving again at 6.

It's not super easy to see what happened to the previous trip before/after, because of stuff like #361. In this case, the path didn't change, but there was a 4 min delay at Henderson and Rainier. Unrealistic for a bike, when Henderson has a bike lane letting them get to the front... I'll keep digging in; something when wrong here.

But the bigger picture: even though we've gotten the scenario to finally run without gridlock, that's just the very first step towards remotely realistic results. The trip table + watching individual trips makes it possible to find and fix more issues (like route choice in this case -- I'm not sure most cyclists would use Rainier at all right here). But for the purposes of this case study in the immediate term, what do we need to do? I'll think through what the blog post should include and update this soon.

**Comment by dabreegster** [comment]
The cyclist delayed at the left turn:
![Screenshot from 2021-01-27 11-25-34](https://user-images.githubusercontent.com/1664407/106042852-73400800-6092-11eb-849f-6e42282488b4.png)
This is a consequence of the weird lane-changing model and a choice made about what turns are generated. The map has a left turn from the bike lane here. It probably shouldn't the bike should be forced to merge into the road for that last step.
![Screenshot from 2021-01-27 11-27-17](https://user-images.githubusercontent.com/1664407/106042979-9ff41f80-6092-11eb-9fd8-244c3aaffacf.png)
Bus lanes also work this way -- buses are allowed to cut in front of all lanes and turn left from the rightmost lane. Since OSM doesn't tend to encode per-lane turn restrictions like this, I think https://github.com/dabreegster/abstreet/blob/cf5ce637f3dedef8bd144c2ab1e4f231b475553a/map_model/src/make/turns.rs#L325 would be the place responsible for filtering this out.

Fixing this is important (and may help/hurt gridlock in other maps, who knows), but I'd like to figure out if it's necessary for the sake of this blog post.

**Comment by michaelkirk** [comment]
Nice rundown - Thanks!

**Comment by dabreegster** [comment]
Unpinning this issue because of uncertainty around the next steps for an immediate blog post. The SDOT policy has been published: https://sdotblog.seattle.gov/2021/01/29/traffic_signal_policy
With details at http://www.seattle.gov/Documents/Departments/SDOT/TechnologyProgram/Pedestrian_Signal_Timing_Policy_January_2021_signed.pdf

**Comment by dabreegster** [comment]
No plans to do anything further here
