### ISSUE TITLE
Throughput layer improvements

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#456]
@Robinlovelace suggested

1) Select a mode to see where most people are walking
2) As you hover over the red gradient slider, show roads on the map matching that high/low range

**Comment by dabreegster** [comment]
@Robinlovelace, the first item now works:
![screencast](https://user-images.githubusercontent.com/1664407/106505438-2cc91f80-647d-11eb-9299-6d95212985f3.gif)
There's some further refinement possible -- people probably don't usually care about buses vs trains. I think separately counting transit riders from transit vehicles could be useful sometimes, though.

**Comment by Robinlovelace** [comment]
Very, very cool. A real-time, multi-modal implementation of the '[travel flow aggregation](https://journals.sagepub.com/doi/10.1177/2399808320942779)' method by me and @mem48? Seems so, very impressive. I deem this issue done.

**Comment by dabreegster** [comment]
There are lots of good design ideas in that paper that we might try borrowing -- particularly using line thickness along with color to emphasize things.

I guess the second task is less useful and kind of vague -- we'd have to choose some epsilon window around the exact number somebody happens to mouseover. And it seems like it ought to be easy to find example roads of any range, if the colors are clear enough. So alright, closing out this issue!
