### ISSUE TITLE
Traffic Diverters

### ISSUE THREAD

**Issue by moo** [a-b-street/abstreet#488]
Feature request: Traffic Diverters 

I know that (unlike in the real world), if we use set Turn Restrictions #70 in A/B Street we can be pretty sure that they will be followed 
(I mean, unless the AI people are set to be super-realistic!) 

But as I was adding these new traffic diverters to OSM, I was wondering if there's a way to implement diverters in A/B: 
https://twitter.com/seabikeblog/status/1355379582161965059

My attempt to add to OSM: https://www.openstreetmap.org/changeset/98433445
(I'll probably add "diverter" to OSM suggestions, I'm surprised it isn't anywhere - so I used "divider") 

I had to adjust a bunch of turn restrictions at the intersection - but if we defined a diverter tool in A/B to restrict/allow certain modes, it could automatically set restrictions, depending upon the direction/orientation of the diverter.

**Comment by dabreegster** [comment]
> if we defined a diverter tool in A/B to restrict/allow certain modes, it could automatically set restrictions, depending upon the direction/orientation of the diverter.

At least from the player's perspective, being able to physically see and manipulate a diverter seems like the right way to communicate this kind of mode-specific turn restriction. Other related examples would be Stay Healthy Streets / low-traffic neighborhoods, which're implemented currently as "no through-traffic" zones, but usually have a physical diverter in reality. And this diverter reminds me of https://www.openstreetmap.org/node/7404294442, a vehicle turn lane and little pedestrian island near Jackson. Yet another kind-of-related diverter is https://www.openstreetmap.org/way/687616788; physically, there are a bunch of flex posts and planters here, allowing bikes but not vehicles.

It might be a while before I give #70 some attention, but also modelling diverters would be part of that work. Thanks for the new examples!

**Comment by moo** [comment]
> And this diverter reminds me of https://www.openstreetmap.org/node/7404294442, a vehicle turn lane and little pedestrian island near Jackson
These are great examples! The center pedestrian island reminds me that a Center Turn Lane feature may be a good first step. Going from a 4-lane to 2-lane + Turn-lane would be a great option, and I'm not sure if that's currently underway? (And if considering size restraints, would let us do more with the roadway)

**Comment by dabreegster** [comment]
> I'm not sure if that's currently underway

![Screenshot from 2021-02-01 08-52-40](https://user-images.githubusercontent.com/1664407/106490782-07cbb100-646b-11eb-844c-bae101639eb6.png)
Center turn lanes are drawn (from OSM's [centre_turn_lane](https://wiki.openstreetmap.org/wiki/Key:centre_turn_lane) or `lanes:both_ways`), but routing and the simulation totally ignore them, and they're not editable currently. https://github.com/a-b-street/abstreet/issues/382#issuecomment-730806495 has a little discussion about modelling vehicles turning left into/out of driveways. I think there's a growing list of missing simulation features that're influencing later decisions.

**Comment by dabreegster** [comment]
Closing this issue, since http://ltn.abstreet.org now exists. That's a tool dedicated totally to studying modal filters. There's a vague idea that it'll eventually be useful to make this kind of edit in the A/B Street simulation too, but I have no plans to get to that anytime soon
