### ISSUE TITLE
Feature request: trains

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#500]
Note: this might be better characterized as a subset of issue #372. If so, my apologies, I will close this one (or someone else can).

It would be fun to have realistic light rail trains on the Seattle map because:
1) Trains!
2) The dynamics of temporary closures at railroad tracks are an important part of the traffic dynamics in some parts of some cities
3) It would also be interesting to see how big clumps of pedestrians exiting train stations would fare in the model.
4) It would force the issue on some kind of "don't block the box" penalty for drivers crossing the train tracks along MLK in Seattle.  
5) For bonus points, introduce some slow freight trains to wreak havoc on traffic in Sodo and downtown Seattle.
6) It would be super fun to model rail system expansions (ST4? ST5?), though that is a ways off (it would require a way to edit or create right-of-way that is outside of the existing lane editor, for example, as well as a way to add stations).

**Comment by dabreegster** [comment]
All of the public transit stuff is kind of hold, and I would say all of this is perfectly in scope for #372. So for the sake of consolidation, going to copy your ideas over there. I'm especially excited about the 6th idea -- #67 is increasingly something I want to focus on.
