### ISSUE TITLE
Add 'background traffic' user interface element for A/B Street in ActDev

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstreet#539]
Currently the A/B Street launches with the Baseline scenario generating traffic only from the development site of interest, e.g. in Allerton Bywater ~10 miles from central Leeds: http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--actdev=allerton_bywater

This is great at showing that this is a car dominated area with the majority (still only ~30, wondering if there should be more - I should check the scenario code) of trips being by car at 08:30

![image](https://user-images.githubusercontent.com/1825120/109353266-0d52c600-7874-11eb-962c-f54aa064343c.png)

Conversely the Go Active scenario shows that the area has substantial walking and cycling potential with more than a four fold increase in the number of bikes on the road:

![image](https://user-images.githubusercontent.com/1825120/109353665-95d16680-7874-11eb-8982-8aa605c284b6.png)

The feature request is a button to add background traffic, could look something like this.

Before:

![image](https://user-images.githubusercontent.com/1825120/109354442-bb12a480-7875-11eb-9e56-81db0b627008.png)

After:

![image](https://user-images.githubusercontent.com/1825120/109354510-d087ce80-7875-11eb-953c-2c60d01bfdcf.png)

Note Walking before cycling, as part of my campaign to emphasise walking above cycling on this project. There are probably good ready-to-go icons to represent background traffic and just a car would do. Thoughts? You can take a look at and modify the sketches online here: https://excalidraw.com/#room=603cf851c0627dc06eba,3LzAuyjOx8Z3qBroALXwuQ

**Comment by Robinlovelace** [comment]
> still only ~30, wondering if there should be more - I should check the scenario code

On that note, I just did a sanity check and it's encouraging, it's just a relatively small site:

```
> # There 289 finished trips under the Go Active scenario for Allerton Bywater
> l = sf::read_sf("data-small/allerton-bywater/desire-lines-few.geojson")
> sum(l$trimode_base)
```

vs

![image](https://user-images.githubusercontent.com/1825120/109355682-77b93580-7877-11eb-92ac-1c76df1d9f50.png)

**Comment by dabreegster** [comment]
ACK on the UI changes.

Some ideas on generating the bg traffic:
- If you have aggregated desire line / OD data for all of these areas anyway, we could just plug it into the R pipeline. No need to just limit to generating people living the development.
- The "home to work" scenario could work, but it often guesses very poorly about the total population in a map, and winds up being very slow to initially generate.
- We could make some kind of lazy/dynamic spawner. Every 15 sim-minutes, it checks the number of active people on the map. If it's too low, it randomly picks some houses and workplaces and a mode just based on Euclidean distance (to be nice and fast in the web version). We could hardcode one value for number of bg agents to use for all actdev maps, or make it be a linear function of the number of buildings in the map, or something else simple to come up with.
- We could add lunch trips to some percent of all people, by picking some food-like place near the workplace.
- We should make all of the abstr-generated people return home in the evening.
- For changes like these last two, I can quickly implement this in Rust, adding some new options to the `import_traffic` tool and triggering them when we see input with a person taking a single trip. Later, we can also port it to `abstr` if desired.

**Comment by Robinlovelace** [comment]
>     * If you have aggregated desire line / OD data for all of these areas anyway, we could just plug it into the R pipeline. No need to just limit to generating people living the development.

I like that idea - first port of call I guess, will catch up on how best to import that.

**Comment by Robinlovelace** [comment]
More comprehensive response to the other points:


- If you have aggregated desire line / OD data for all of these areas anyway, we could just plug it into the R pipeline. No need to just limit to generating people living the development.

Think that could be the quickest win on this - will involve trips starting and ending outside the A/B Street region but if that's not an issue think it's well worth doing.

- The "home to work" scenario could work, but it often guesses very poorly about the total population in a map, and winds up being very slow to initially generate.

Point taken and a good reason to explore alternatives.

- We could make some kind of lazy/dynamic spawner. Every 15 sim-minutes, it checks the number of active people on the map. If it's too low, it randomly picks some houses and workplaces and a mode just based on Euclidean distance (to be nice and fast in the web version). We could hardcode one value for number of bg agents to use for all actdev maps, or make it be a linear function of the number of buildings in the map, or something else simple to come up with.

Interesting but unfortunately in some sites though-traffic will be the biggest 'driver' of traffic - will be good to show busy roads serving far away populations. Making use of the traffic data already in the map could help with that but may be prohibitively time-consuming to implement.

- We could add lunch trips to some percent of all people, by picking some food-like place near the workplace.

Really like that idea!

- We should make all of the abstr-generated people return home in the evening.

Another quick win, good point, in my court.

- For changes like these last two, I can quickly implement this in Rust, adding some new options to the import_traffic tool and triggering them when we see input with a person taking a single trip. Later, we can also port it to abstr if desired.

Sounds good. Suggest we chat over the options and maybe even to a 'mini hack' to progress on the quickest wins one day next week.

**Comment by dabreegster** [comment]
UI question: the "bg traffic" button in the design above looks nice, but it's unclear whether it's enabled or not. Here's a checkbox, lined up with the base/active toggle, to make it clear they're related.
![Screenshot from 2021-03-02 09-50-09](https://user-images.githubusercontent.com/1664407/109691987-d8c55f80-7b3c-11eb-935d-510244bf98e0.png)
A 4th button on the row below really stretches the width, and it's unclear the two traffic controls are related:
![Screenshot from 2021-03-02 09-52-41](https://user-images.githubusercontent.com/1664407/109692173-10cca280-7b3d-11eb-8c08-a8c401843502.png)

I'll go with one of these for now, but it's easy to change, and I'm guessing I'm missing an obvious answer. Another consideration: we may want to add another button for sites that have proposed map edits built by us.

**Comment by Robinlovelace** [comment]
These look great, many thanks. I like the bottom one best.

**Comment by dabreegster** [comment]
![Screenshot from 2021-03-02 10-37-58](https://user-images.githubusercontent.com/1664407/109697691-6015d180-7b43-11eb-934b-c7308dcc5131.png)
For highlighting in-site people, here's one idea for unzoomed. It's hard to see more unzoomed, so I'm going to instead try greying out all the background people instead. Coming soon!

**Comment by Robinlovelace** [comment]
Looks good!

**Comment by dabreegster** [comment]
![Screenshot from 2021-03-02 10-43-50](https://user-images.githubusercontent.com/1664407/109698784-a0c21a80-7b44-11eb-8bf4-146f08a5bd4d.png)
Here's the "fade everyone else" idea. It's lerping 50% between the original color and white. Can keep tuning it, including for night mode.

**Comment by Robinlovelace** [comment]
The interface is done so closing :tada: 

Details can be worked out in terms of implementation but that may be in the ActDev code base. Also possible in this repo. Good redundancy/resilience in the system!
