### ISSUE TITLE
osm_viewer got error response

### ISSUE THREAD

**Issue by cswanghan** [a-b-street/abstreet#550]
I ran into this error while I am trying to run osm_viewer locally by using osm_viewer/run_web.sh.

![image](https://user-images.githubusercontent.com/699970/109765238-8a44bd80-7c2f-11eb-8399-abe981f72fd3.png)

any thoughts?

**Comment by dabreegster** [comment]
The `run_web.sh` scripts are for developing the web version locally. They're brittle -- you have to `cd game; ./run_web` for it to find the right directory. You also need to first do `cargo run --bin updater` and make sure you have some map files downloaded.

If you're trying to run locally, I'd recommend using the native version, not the web. It runs faster. https://a-b-street.github.io/docs/dev/index.html has the first few steps to do that

**Comment by dabreegster** [comment]
So if you want to run the osm_viewer, the minimal setup steps are cloning the repo would be `cargo run --bin updater; cargo run --bin osm_viewer`. Equivalently, you can `cd osm_viewer; cargo run`

**Comment by cswanghan** [comment]
Great, now I have osm_viewer running on my mac. But it looks like there is no edit function and the map_editor module is on a blank map. Is there any way I can edit the existed osm map and export the result for next use?

I have read the document (which is really detailed by the way), but I found no instruction on this feature.

**Comment by dabreegster** [comment]
The map-editing functionality is in the `game` crate. `cd game; cargo run -- --dev`, then "edit map" at the top.
![Screenshot from 2021-03-03 08-50-30](https://user-images.githubusercontent.com/1664407/109841061-88620680-7bfd-11eb-861a-a56ee6b3d5d3.png)
You can click a lane and change its type, reverse it, modify the speed limit, ban through-traffic. You can also modify stop signs and traffic signal timing. The edits are saved automatically as JSON in `data/player/edits/...`. But these edits can't be exported back to OSM; they're not meant for that. A/B Street's editor is about imagining how roads could look with less emphasis on cars.

There are [lots of crates](https://a-b-street.github.io/docs/dev/#code-organization) in the project. `map_editor` is an internal tool for [drawing test maps](https://twitter.com/CarlinoDustin/status/1362940241359736837) and debugging geometry problems. Hopefully in about a month I'll start on #67, which will allow much more general editing in the game directly, like widening roads or creating new ones.

Are you looking for a way to fix OSM tagging problems? Unfortunately `osm_viewer` just renders right now, and the editor in `game` is not designed to fix OSM problems upstream. The only tool that's meant to directly fix OSM is https://a-b-street.github.io/docs/side_projects/parking_mapper.html. If you run it locally, there's a button to generate a `.osmc` that you can load in JOSM and upload. But that tool is specialized for street parking only.

**Comment by cswanghan** [comment]
Thanks for your reply, I am looking for edit map function for now, as you have mentioned above. 

I've tried this function, which is really pretty; I hope there will be a undo function.
