### ISSUE TITLE
Roll out actdev UI changes to all modes

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#551]
@Robinlovelace in https://github.com/cyipt/actdev/issues/112#issuecomment-789573411 reports:
![109784487-07a60900-7c03-11eb-90f7-9c2ad37930f3](https://user-images.githubusercontent.com/1664407/109839942-73d13e80-7bfc-11eb-8094-6a210b958c93.gif)
This example has a particularly long name.

**Comment by Robinlovelace** [comment]
Glad the gif was useful! FYI that was taken on a pretty widescreen monitor:

``` r
system("xdpyinfo | grep dimensions", intern = TRUE)
#> [1] "  dimensions:    3520x1080 pixels (931x285 millimeters)"
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by michaelkirk** [comment]
Combining the "time" panel with the "time controls" panel makes UX sense, and I am happy that it eliminates one of our numerous top-level panels.

It does look like it widened the top left time panel a smidge. 

Here's a couple alternatives I can think of to ameliorate this:

1. get rid of the active trips panel
  a. put mode counts somewhere else - maybe in the bottom right legend?
  b. put finished trips somewhere else - as a monotonic counter, maybe this could make sense in the top-left time panel?
  c. move the "data" button to the list of controls floating left of the minimap


Here's a cut-paste mockup:
<img width="2032" alt="eliminate active trips" src="https://user-images.githubusercontent.com/217057/109992911-97f65380-7cc0-11eb-9028-a4b90063dc4d.png">


2. narrow the top-middle panel
  a. extract the ABStreet logo into a free floating panel at the bottom-left, like where the "home/settings" button normally is
  b. get rid of the "edit map" button, or if we want to keep it, remove the label, and only show "edit map" as a tooltip.
  c. This is incompatible with alternative one, but if we keep the active trips panel, we can move the "walking activity", "cycling activity", etc. controls into a vertical list within the top-right "active/trips" panel
  
Here's a cut-paste mockup:

<img width="2032" alt="narrow-middle" src="https://user-images.githubusercontent.com/217057/109993342-09360680-7cc1-11eb-809e-69bf049d218f.png">

**Comment by dabreegster** [comment]
Thanks for the mockups! Any feedback, @mvl22 and @Siequnu?

> alternative 1: get rid of the active trips panel

The logical grouping of everything moved around makes sense to me. I like this design a lot, but the top-right panel feels a little strange visually. I would almost expect it to be centered, even though that clutters more of the map and is inconsistent with the other panels nestled snugly in corners.

> alternative 2: narrow the top-middle panel

My main concern here is the loss of vertical space on the right. Even now, when we open up some of the layers, the panel eats into the minimap and finished trips panel:

![Screenshot from 2021-03-04 08-34-53](https://user-images.githubusercontent.com/1664407/109996893-81ea9200-7cc4-11eb-83d4-314e4e282a4c.png)
![Screenshot from 2021-03-04 08-34-43](https://user-images.githubusercontent.com/1664407/109996900-83b45580-7cc4-11eb-9ab7-81107a8ecdf2.png)

**Comment by mvl22** [comment]
> Here's a cut-paste mockup

Whatever you do, please make sure that panels at the same vertical position are the same height :) (Of course I realise that was a mockup, but this remains such a glaring design mismatch at present.)

![Screenshot 2021-03-04 at 19 08 15](https://user-images.githubusercontent.com/361423/110016490-ff41f100-7d1c-11eb-98ef-f686e4e36529.png)

> Thanks for the mockups! Any feedback, @mvl22 and @Siequnu?

Is the height of those panels actually fixed? I.e. can they expand downwards to fill the space? (Again, with the heights kept in sync.)

Fundamentally, you can't really deal with smaller screens and responsive widths unless you allow the widths to become smaller and thus the heights to be enlarge, or shrink font sizes progressively. I don't know if the framework you are using allows the kind of flexibility that CSS does (once you understand the quirks in its slightly odd float model!).

**Comment by Robinlovelace** [comment]
Update on the latest version: on my slightly smaller (but still big) monitor I see this for Aylesham, not a long name:

![image](https://user-images.githubusercontent.com/1825120/110218787-7f01c400-7eb3-11eb-9fe8-99d6979f4b28.png)

I definitely think this is worth fixing. Looking at the alternative suggestions by @dabreegster above I'm not sure which is best and may have another suggestion...

**Comment by Robinlovelace** [comment]
Suggestion: combine the Active trips with time panel. It's clear from the 'Finish trips' text that this is talking about trips so I think the 'Active trips' text could be removed. Thoughts?

![image](https://user-images.githubusercontent.com/1825120/110219217-d3a63e80-7eb5-11eb-8585-271598e83337.png)


Editable version of this sketch: https://excalidraw.com/#room=17b549ad29444653b500,jbpQu4KsdRXiZ6aCedEQuQ

**Comment by dabreegster** [comment]
> Update on the latest version: on my slightly smaller (but still big) monitor I see this for Aylesham, not a long name:

Whoops, my most recent deploy didn't include the `actdev_panel_changes` branch. That still wouldn't help with the width issue, though.

> combine the Active trips with time panel.

This is similar to Michael's alternative 1, which I like a lot. I'll try this out in that branch.

**Comment by dabreegster** [comment]
![Screenshot from 2021-03-06 17-11-15](https://user-images.githubusercontent.com/1664407/110225937-fbd67300-7e9e-11eb-87f7-7670db9ad9da.png)
The consolidation is working pretty well, but the 4 buttons on the actdev panel are just wide. I'm going to try some more adjustments.

**Comment by Robinlovelace** [comment]
Looking good.

**Comment by dabreegster** [comment]
![screencast](https://user-images.githubusercontent.com/1664407/110226012-e7df4100-7e9f-11eb-9203-211e21d322e0.gif)
I'm pretty happy with this, will deploy soon. Any other ideas?

This change affects other gameplay modes. I'm liking this new layout. If we want to commit to it everywhere, need to still work on:

- folding challenge mode results into the top center panel, instead of trying to line up under the time panel
- maybe moving all top-center gameplay panels to the right, like actdev
- Maybe moving layers to the left, to avoid the vertical space crunch with the minimap. Except it'll collide with info panels... maybe those could become mutex.

All of this needs consultation with Yuwen before finalizing everywhere.

**Comment by Robinlovelace** [comment]
> Any other ideas?

One more idea: can the top left panel be the same height as the top right one to keep @mvl22 happy?

Overall it's definitely better so please deploy whenever is good. Hoping to push a load of data soon so may want to wait until updated scenarios (pretty minimal changes).

**Comment by dabreegster** [comment]
> One more idea: can the top left panel be the same height as the top right one to keep @mvl22 happy?

This is actually kind of hard to do properly based on how our layouting currently works, but I'll find at least a temporary hack to make it work.

**Comment by dabreegster** [comment]
![Screenshot from 2021-03-07 11-20-07](https://user-images.githubusercontent.com/1664407/110251801-16f4c180-7f37-11eb-9525-823ace313983.png)
Panel height is now synced up.

I think all of the reported problems have been fixed. I'm going to repurpose this issue for making the changes apply for abst generally, pending design discussion.

**Comment by dabreegster** [comment]
#557 drafted for the eventual design discussion

**Comment by Robinlovelace** [comment]
This looks great to me - job done on this mega issue? Almost I reckon!

**Comment by dabreegster** [comment]
> This looks great to me - job done on this mega issue? Almost I reckon!

I think we're done from the actdev perspective. Since there's so much good discussion here, I renamed the issue and plan to wait a few weeks until Yuwen, Michael, and I can discuss these changes and if we should use them everywhere.

**Comment by dabreegster** [comment]
Meeting notes:

All of the actdev changes can be rolled out generally, with a few adjustments. I'll do this later today.

- Left-align time in the time panel
- Try combining the mode counters in the minimap with the checkboxes into a single row
- Moving all of the top-center panels to the top-right is fine
- Adjusting the info panel to not run into the taller time+speed panel

A next step is making layers and info panels mutually exclusive, and moving them both to the left. This should alleviate vertical space running out when zoomed in with the minimap and layers open.

Michael's going to transform the time bar and finished trip counter into a single bar, showing comparison with baseline when that makes sense.

A few longer-term ideas, probably not going to touch until next quarter:

- Allow the layers panel to be minimized. Always open a new one full; don't be sticky.
- Enable the info panel and layer panel to be draggable.
- Blur beneath the panels instead of increasing opacity so much
- Launch Santa and the 15m tool from the main menu of A/B Street, even though they're now separate apps
- Manually minimize the minimap when zoomed in. This decision is sticky.

**Comment by dabreegster** [comment]
Since all of the stuff discussed in this issue is now done, I'm going to close it out. I moved the remaining tasks to #331, which is sort of our catch-all UI backlog.
