### ISSUE TITLE
Generate travel demand for actdev

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#556]
For the actdev integration, @Robinlovelace has used https://github.com/a-b-street/abstr/ to disaggregate some desire lines in the UK and create abst scenarios. He's now in the process of generalizing the approach to create background traffic, not just model people living in particular development sites. I'm going to reimplement everything in Rust, partly to have a comparison of approaches, and partly to mitigate schedule risk before the deadline next week. Longer term, this can be one option for #424 when this sort of OD data is available.

References for the R version:
- https://itsleeds.github.io/pct/reference/get_od.html
- https://github.com/cyipt/actdev/blob/main/code/abstr-scenarios.R
- Source data is https://www.statistics.digitalresources.jisc.ac.uk/dataset/wu03uk-2011-sms-merged-lala-location-usual-residence-and-place-work-method-travel-work

The raw data's at https://s3-eu-west-1.amazonaws.com/statistics.digitalresources.jisc.ac.uk/dkan/files/FLOW/wu03uk_v3/wu03uk_v3.csv. Each row has (from, to, number of commuters by mode). Trying to hunt down a geojson of the zones... The main site points me to https://wicid.ukdataservice.ac.uk/cider/wicid/info.php?geogtype=96&guest=1 without any actual coordinates. Found a few other places, like https://ons.maps.arcgis.com/home/item.html?id=2dc879e2df52482ba764d3c11cc3150b, but yet to find the coordinates of each of these zones. Not just the centroid!

Anyway, I think the general approach I drafted at https://github.com/a-b-street/abstr/pull/4 will work. Assuming all abst structures as input:

```
struct DesireLine {
  from_zone: String,
  to_zone: String,
  mode: Mode,
  number_trips: integer,
}

/// Each DesireLine describes a number of trips using a certain mode that goes from zone1 to zone2. For each 
/// of those trips, randomly select a residential building in zone1 and a commercial building in zone2, and create a person performing that trip. If the zone is outside out-of-bounds, snap to a border instead.
fn disaggregate_desire_lines(
  map: &Map,
  zones: Map<String, Polygon>,
  desire_lines: Vec<DesireLine>,
) -> Vec<PersonSpec>
```

There's no special handling for people in the site or not.

`DesireLine` is straightforward to create from the CSV I found. Only remaining challenge is finding the geometry per zone.

**Comment by Robinlovelace** [comment]
Great to be attacking this issue from multiple angles. I can certainly help here:

> Trying to hunt down a geojson of the zones.

See https://github.com/cyipt/actdev/releases/download/0.1.13/zones_core.geojson

Code to generate and upload that file:

```r
# zones = pct::get_pct(geography = "msoa", layer = "z", national = TRUE)
zones = sf::st_as_sf(readRDS("~/npct/pct-outputs-national/commute/msoa/z_all.Rds"))
names(zones)
zones_core = zones[1:13]
names(zones_core)
sf::write_sf(zones_core, "zones_core.geojson")
piggyback::pb_upload(file = "zones_core.geojson", repo = "cyipt/actdev")
piggyback::pb_download_url(file = "zones_core.geojson", repo = "cyipt/actdev")
```

**Comment by dabreegster** [comment]
@Robinlovelace Thanks for the pointers! I'm making solid progress on the new pipeline, but I'm unable to match up geocodes between the OD data (https://s3-eu-west-1.amazonaws.com/statistics.digitalresources.jisc.ac.uk/dkan/files/FLOW/wu03uk_v3/wu03uk_v3.csv) and https://github.com/cyipt/actdev/releases/download/0.1.13/zones_core.geojson. In Poundbury for example, I've matched geo_codes like [E02004277](https://mapit.mysociety.org/area/45350.html) and [E02004278](https://mapit.mysociety.org/area/38157.html). But the CSV doesn't have any from/to areas named like this. It has areas like "95AA", "E41000324", "S12000021", etc. According to the CSV's page, the geographies are "UK Local Authorities (merged) 2011" and "2011 UK SWS additional workplace codes". I'm still overwhelmed by all of the UK geography terms, but your script pulled from "msoa" -- do we want "lsoa" instead? Is there a raw source for this data? From the notes in `pct`, some of the files you originally used disappeared.

**Comment by Robinlovelace** [comment]
Aha, will take a look...

**Comment by Robinlovelace** [comment]
OK yes I think I gave you the LSOA data - apologies, more soon...

**Comment by Robinlovelace** [comment]
Think I've figured it out: the dataset you found @dabreegster was not the MSOA-MSOA data.

<details>

```
> u = "https://s3-eu-west-1.amazonaws.com/statistics.digitalresources.jisc.ac.uk/dkan/files/FLOW/wu03uk_v3/wu03uk_v3.csv"
> od_data = readr::read_csv(u)

── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  `Area of usual residence` = col_character(),
  `Area of workplace` = col_character(),
  `All categories: Method of travel to work` = col_double(),
  `Work mainly at or from home` = col_double(),
  `Underground, metro, light rail, tram` = col_double(),
  Train = col_double(),
  `Bus, minibus or coach` = col_double(),
  Taxi = col_double(),
  `Motorcycle, scooter or moped` = col_double(),
  `Driving a car or van` = col_double(),
  `Passenger in a car or van` = col_double(),
  Bicycle = col_double(),
  `On foot` = col_double(),
  `Other method of travel to work` = col_double()
)

> od_data_dk = readr::read_csv(u)

── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  `Area of usual residence` = col_character(),
  `Area of workplace` = col_character(),
  `All categories: Method of travel to work` = col_double(),
  `Work mainly at or from home` = col_double(),
  `Underground, metro, light rail, tram` = col_double(),
  Train = col_double(),
  `Bus, minibus or coach` = col_double(),
  Taxi = col_double(),
  `Motorcycle, scooter or moped` = col_double(),
  `Driving a car or van` = col_double(),
  `Passenger in a car or van` = col_double(),
  Bicycle = col_double(),
  `On foot` = col_double(),
  `Other method of travel to work` = col_double()
)

> od_data = pct::get_od()
No region provided. Returning national OD data.
trying URL 'https://s3-eu-west-1.amazonaws.com/statistics.digitalresources.jisc.ac.uk/dkan/files/FLOW/wu03ew_v2/wu03ew_v2.zip'
Content type 'application/zip' length 12409884 bytes (11.8 MB)
==================================================
downloaded 11.8 MB


── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  `Area of residence` = col_character(),
  `Area of workplace` = col_character(),
  `All categories: Method of travel to work` = col_double(),
  `Work mainly at or from home` = col_double(),
  `Underground, metro, light rail, tram` = col_double(),
  Train = col_double(),
  `Bus, minibus or coach` = col_double(),
  Taxi = col_double(),
  `Motorcycle, scooter or moped` = col_double(),
  `Driving a car or van` = col_double(),
  `Passenger in a car or van` = col_double(),
  Bicycle = col_double(),
  `On foot` = col_double(),
  `Other method of travel to work` = col_double()
)


── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  MSOA11CD = col_character(),
  MSOA11NM = col_character(),
  BNGEAST = col_double(),
  BNGNORTH = col_double(),
  LONGITUDE = col_double(),
  LATITUDE = col_double()
)

> nrow(od_data) / od_data_dk
Error in FUN(left, right) : non-numeric argument to binary operator
> nrow(od_data) / nrow(od_data_dk)
[1] 21.80608
```

**Comment by Robinlovelace** [comment]
Looking at the source code, I think this is the URL that the `get_od()` function gets: https://github.com/ITSLeeds/pct/blob/master/R/desire_lines.R#L81-L84

**Comment by dabreegster** [comment]
Ahh, I'm not sure where I got the other filename. `wu03ew_v2` works. Thank you!

**Comment by dabreegster** [comment]
This is done! https://github.com/a-b-street/abstreet/blob/master/popdat/src/od.rs has all the (commented!) logic for disaggregation, and https://github.com/a-b-street/abstreet/blob/master/importer/src/uk.rs parses the raw data and handles merging background traffic with the base/go active scenarios. The UI has been updated to toggle these scenarios; the version live on the site should be updated within the hour.

I'm not sure what sort of validation to do to make sure the results look sane, other than watching the simulations and using the commuter viz tool. I haven't checked things super carefully, but the results seem reasonable. The scenarios gridlock in most of the maps; this is totally expected.

My next step is likely to get the background scenarios to **not** gridlock. Simplest strategy might be to just uniformly scale down the number of people by some percent, hand-tuning.

**Comment by Robinlovelace** [comment]
Great work @dabreegster :tada:
