### ISSUE TITLE
Mode counts seem to be static in latest version of ActDev simulations

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstreet#558]
Was just checking out the latest version of the UI after great work on #551. It looks awesome IMO. One issue though: the counts for different modes seem to not change. Also wondering how the UI will respond when counts go above 100 or even 1000, should be fine but thought it worth asking.

![Peek 2021-03-07 20-47](https://user-images.githubusercontent.com/1825120/110254381-d91f8980-7f86-11eb-82a0-8e5cfaa344a6.gif)

Source: https://actdev.cyipt.bike/abstreet/?--actdev=allerton-bywater&--cam=14.90/53.74907/-1.36466

**Comment by dabreegster** [comment]
Wooo, good catch. The minimap panel doesn't respond to time changing. Will fix, and also see how the layout looks with larger numbers.

**Comment by dabreegster** [comment]
![screencast](https://user-images.githubusercontent.com/1664407/110384725-e5512880-8012-11eb-85ee-d25f9985812d.gif)
The counters definitely jump a bit visually as the width changes. Same as the top-left time. If there are ideas to improve this, I'm happy to implement, but otherwise, I think this is fixed.

(I'll deploy a new actdev build with more fixes tonight)

**Comment by dabreegster** [comment]
Edit: Michael fixed the top-left time from jumping by using a fixed-width font. We can't play the same trick for counts unless we pad with spaces and assume some reasonable max (probably 100,000)

**Comment by Robinlovelace** [comment]
Very cool! Definitely good enough. First thought: the horizontal side-by-side representation of the modes that happens when you zoom in feels a bit easier on the eye. But may not be worth changing anything else until after the dust has settled and others have had a chance to chime in. Overall, awesome work, I hope some of this feeds into the main UI, I think it's a step forward. Impressive.
