### ISSUE TITLE
Zooming without a scroll wheel

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#559]
Martin brought up that not everybody has a trackpad with pinch-scrolling or a mouse with a scroll wheel. All they could do today is enable an option in settings to "use arrow keys to pan and Q/W to zoom", but they'd have to discover this.

How should we handle this? Google Maps and the OSM slippy viewer have +/- icons on the map. We've been trying to consolidate the number of on-map buttons, but maybe we should reconsider here.

**Comment by michaelkirk** [comment]
I'd be in favor of adding zoom buttons. 

In general, I think if OSM, MapBox, and GoogleMaps agree on something, it's safe to assume our users will expect it to work that way too.

**Comment by dabreegster** [comment]
Ungap and LTN have these
![Screenshot from 2022-09-16 09-00-17](https://user-images.githubusercontent.com/1664407/190534222-b93ed4d5-ddbc-4122-a5b9-85bd7b828351.png)
