### ISSUE TITLE
Smooth zooming

### ISSUE THREAD

**Issue by ChildishGiant** [a-b-street/abstreet#564]
It'd be lovely if zooming could be smoothed out so it's not so jarring and choppy.

**Comment by dabreegster** [comment]
Have you tried the [native version](https://github.com/a-b-street/abstreet/releases)? It runs way more smoothly. The web version is also choppy for me, and I don't think it's a hardware issue. Part of the problem might be unavoidable -- WebAssembly and executing code in a browser likely has inherent overhead. But the [core event loop](https://github.com/a-b-street/abstreet/blob/edf3914e4dc633e59462d431b282302668e46f91/widgetry/src/runner.rs#L314) almost definitely isn't written to be maximally performant. Maybe it could buffer the input events from scrolling in/out, or drop drawing frames when things get slow.

**Comment by dabreegster** [comment]
There was some constant scaling factor in the web version that I adjusted a few weeks back. See if the web version (ltn.abstreet.org) feels any better

**Comment by ChildishGiant** [comment]
I think what I may have meant was a smooth transition between zoom states. OSM fudges this and google maps has a very smooth implementation

https://user-images.githubusercontent.com/13716824/191017813-161f5926-f40a-442a-921a-67fddddf754e.mp4

**Comment by dabreegster** [comment]
Ah, I see. A/B Street has two main zoom levels, and they suddenly switch without any smooth transition. The Google example does a good job of gradually showing more detail about buildings and moving labels gently. I'd love to keep improving the transition in A/B Street, but I don't have any specific ideas right now
