### ISSUE TITLE
Use case: the A5 in London

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#577]
The goal is to model cycle lanes along [LCN route 5](https://www.openstreetmap.org/relation/11248082).

As a first step, I'm importing a map along most of this area. The [geofabrik region](http://download.geofabrik.de/europe/great-britain/england/greater-london.html) cuts off around Edgware, so for now it stops there. We may want to chop this study into a few smaller maps anyway for performance.

CC @Robinlovelace

**Comment by dabreegster** [comment]
Some next steps:

- Get the map to not gridlock
- Go along the route and see if the road is imported sanely. Are the number of lanes realistic? What's the idea of the change -- is there spare shoulder room or lanes to convert, or do we make part of the road one-way to cars and use the other half for cycletracks?
- Figure out a saner way to make a bulk edit of this fashion along a long route. I had the same UX issue for Poundbury.

Aside: there's a road called [Shoot-up Hill](https://www.openstreetmap.org/way/98729910). Inquire what this means in UK lingo. It's frighteningly druggy to my American ears.

**Comment by matkoniecz** [comment]
https://londonist.com/2016/04/how-london-s-hills-got-their-names claims

> Turn left out of Kilburn tube and you'll encounter this curious name, which covers the stretch of the Edgware road between the station and Cricklewood. It has nothing to do with drug abuse, nor gun crime, but is thought to be a reference to the way the old Roman road shoots suddenly upward just after the station. We're not 100% convinced by this, but other theories are hard to come by.

**Comment by eldang** [comment]
I grew up in London.  In fact my parents now live very close to the S end of that proposed bike route.  

Shoot-up Hill always made me laugh, and it means the same thing you're thinking.

**Comment by dabreegster** [comment]
![Screenshot from 2021-06-03 17-20-49](https://user-images.githubusercontent.com/1664407/120727709-16b18700-c490-11eb-87fa-1f66a62c6fe0.png)
Starting to look at this. LCN route 5 runs parallel to the A5 for a while, but around the Kilburn station, it joins the road. That's probably where we want to focus.

At a quick glance, according to OSM, it's just 1 lane each direction and a sidewalk on both sides.
![Screenshot from 2021-06-03 17-22-39](https://user-images.githubusercontent.com/1664407/120727809-58423200-c490-11eb-81f4-b53e331687fe.png)
Streetview actually shows what looks like a cycletrack there:
![Screenshot from 2021-06-03 17-23-51](https://user-images.githubusercontent.com/1664407/120727882-80319580-c490-11eb-91df-78c8d413d11a.png)
Slightly further up, it becomes a bus lane, with the road width fluctuating a bit.

We can now modify road width in A/B Street, do things like transform one regular lane into a two-way cycletrack, and easily apply the change along a section of the A5. I think the next steps are:

1) Find an OSM mapper in or familiar with London who's interested in fixing up the tagging along here
2) Getting a better idea of what part of the A5 could use some changes, and what the changes are

**Comment by matkoniecz** [comment]
> Find an OSM mapper in or familiar with London who's interested in fixing up the tagging along here

Posted to talk-gb

**Comment by dabreegster** [comment]
I had chatted with a cycling advocate named [Brian Deegan](https://twitter.com/bricycle), and he had been interested in imagining a path along the A5 all the way up to St Albans. I'm waiting to hear back about details of this idea. Is there another route from central London headed that direction that exists or is planned?

**Comment by systemed** [comment]
Ah, gotcha. I'm not aware of a planned route but Brian is much more knowledgeable about these things than I am!

**Comment by dabreegster** [comment]
I just cleaned up this old study area, after importing most boroughs instead. If studying this corridor becomes an interest again, we can reopen and find some next steps
