### ISSUE TITLE
Improve LCID import

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#601]
LCID = Leeds climate innovation district, https://www.openstreetmap.org/#map=17/53.78913/-1.53430

From comparing abst's rendering to OSM, I don't spot many cases where we're totally missing roads in OSM. The few that are missing:
- https://www.openstreetmap.org/way/775983562, skipped because `service=parking_aisle` is only used for parking lots
- https://www.openstreetmap.org/way/803329641, connecting the north end of citu bridge with Secret Garden. It's `highway=steps`, but also `construction=cycleway` and a few other things...

There's also some complex intersections around here that we could try to adjust:
![Screenshot from 2021-04-11 16-27-28](https://user-images.githubusercontent.com/1664407/114325056-e29a9500-9ae2-11eb-8749-7d5ce4bede31.png)

**Comment by dabreegster** [comment]
> https://www.openstreetmap.org/way/803329641

@Robinlovelace, https://www.flickr.com/photos/97888609@N02/51109825878 are the stairs here, right? Is anything here still under construction? And it looks cyclists just have to carry on the steps here?

**Comment by Robinlovelace** [comment]
> @Robinlovelace, https://www.flickr.com/photos/97888609@N02/51109825878 are the stairs here, right?

Correct, the stairs are just on the LCID side of the river.

> And it looks cyclists just have to carry on the steps here?

No there's a ramp.

**Comment by dabreegster** [comment]
https://www.openstreetmap.org/way/862793361
Do import `highway=steps`, allow bike access but penalize it significantly. Ideas for rendering?

**Comment by dabreegster** [comment]
![Screenshot from 2021-04-11 17-24-07](https://user-images.githubusercontent.com/1664407/114326672-bd118980-9aea-11eb-98c0-12cbf0224eaf.png)
Bridge geometry explodes

**Comment by dabreegster** [comment]
I attempted some OSM fixes yesterday. Sort of better...
![bridge](https://user-images.githubusercontent.com/1664407/114575660-3f0acb00-9c2f-11eb-94b0-530ce639d6e1.png)

**Comment by Robinlovelace** [comment]
Good to go IMO.

**Comment by dabreegster** [comment]
Closing, since the biggest problems are fixed via upstream OSM edits. There are existing issues covering highway=steps.
