### ISSUE TITLE
Importing own network (Windows 10)

### ISSUE THREAD

**Issue by tungchifung** [a-b-street/abstreet#602]
Hi,

I tried to import my own network with the build-in function in ABStreet and the command line function. I tried the .37 .38 .39 version and all result in crashes or very long time (30 mins) with no CPU or GPU usage. I am using a small area of the NYC Manhattan as a test.

Using the build-in function in ABStreet have no log in text box. Just have the timer of loading time. The log is attached
0.38 [output.txt](https://github.com/a-b-street/abstreet/files/6299899/output.txt)

I let it ran for over 30 mins and gave up. Here is the log 
0.39 [output.txt](https://github.com/a-b-street/abstreet/files/6299919/output.txt)

Using command line function result in the following screen cap:
![Capture](https://user-images.githubusercontent.com/11725332/114464393-9da75900-9bdd-11eb-9b2f-ec91868d9ba1.JPG)

**Comment by dabreegster** [comment]
It looks like `importer` fails immediately because some of those commands aren't found, but the UI doesn't pick up the failure. I'll work on fixing both problems.

Since the fix won't be available before next Sunday's release, in the meantime, we're importing part of Manhattan now. You could try the "Download more cities" button and select "us/nyc", or on the web: http://abstreet.s3-website.us-east-2.amazonaws.com/0.2.39/abstreet.html?--dev&system/us/nyc/maps/lower_manhattan.bin

**Comment by dabreegster** [comment]
Hmm, I can't figure out why the UI doesn't see the failure. If I force `importer` to crash, the error shows up in the UI immediately. https://github.com/a-b-street/abstreet/blob/master/map_gui/src/tools/command.rs uses crates.io/crates/subprocess, and there must be some differences between Windows and Linux+Mac. I'll keep poking around.

The root problem is that `importer` demands those 3 commands exists, even though it shouldn't need to use any of them. I'll fix that.

**Comment by dabreegster** [comment]
I've fixed the main issue but discovered another: when the importer prints warnings, sometimes those happen to wind up after `one_step_import` prints the map name. The whole process uses the very last line of output to figure out what the new map is called. This is brittle! I'll use a different way to communicate that back.

**Comment by dabreegster** [comment]
I believe all of the problems have been fixed; everything will be available in the next release this Sunday. Thanks so much for reporting, and let me know if you hit any other problems!
