### ISSUE TITLE
grid2demand file picker hangs on macos

### ISSUE THREAD

**Issue by michaelkirk** [a-b-street/abstreet#605]
Seems like the newly integrated file-picker stuff hangs on macos.

https://user-images.githubusercontent.com/217057/114619824-ce2fd700-9c5f-11eb-881c-cc17d49528b7.mov

You can't really tell from the video, but the app becomes unresponsive after presenting the file picker dialog, and must be externally killed. My guess is that we've induced deadlock by waiting on the wrong thread.

In a bit of fascinating trivia, the "beach ball" cursor that I actually see on my desktop is not reflected by the screen capture video. 🤷

**Comment by dabreegster** [comment]
https://github.com/a-b-street/abstreet/blob/f8583b9e36660bb447d9da07c048d5eda6d1a038/game/src/sandbox/gameplay/freeform/grid2demand.rs#L11
I guess we can't take the easy way out after all. :(   They have an async version, I'll try switching to that. I know there's also a requirement on mac to spawn the dialog from the main thread, but we should already be doing that. https://github.com/PolyMeilex/rfd#diference-bettwen-macos-windowed-app-and-macos-nonwindowed-app
