### ISSUE TITLE
Wrong junction geometry with Modify Entire Road tool

### ISSUE THREAD

**Issue by tungchifung** [a-b-street/abstreet#655]
I was playing around with the experimental Modify Entire Road and encounter some issue with the tool. I deleted a lane and add back a lane then the junction become insanely huge and the road link turns into a tiny segment. Here is a screen shot.

![3](https://user-images.githubusercontent.com/11725332/118850839-137f9e00-b8c9-11eb-8378-aba4a0e33bf3.JPG)

**Comment by dabreegster** [comment]
Thanks for reporting! This is a known issue, and one of the main reasons the editor is still "experimental." I have a few ongoing attempts to fix this; I'll keep this issue updated

**Comment by dabreegster** [comment]
![Screenshot from 2021-05-19 14-17-50](https://user-images.githubusercontent.com/1664407/118885748-02c12f00-b8ad-11eb-98cf-ce4efacd4822.png)
I think I've fixed the problem of intersections growing, but introduced a bug with the sidewalk connections. Looking into that
