### ISSUE TITLE
Visualizing low-traffic neighborhoods and gated communities

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#660]
Today, there are two types of roads colored pink.

![Screenshot from 2021-05-21 14-06-49](https://user-images.githubusercontent.com/1664407/119198214-cf61da00-ba3d-11eb-9211-de9b3ad89fa5.png)
This is a gated/private community in Seattle called Broadmoor. There's a physical gate surrounding this neighborhood; you have to show an ID to a guard to walk or drive in.

![Screenshot from 2021-05-21 14-08-40](https://user-images.githubusercontent.com/1664407/119198367-0e902b00-ba3e-11eb-9386-c33b07ed6e5d.png)
This is a Stay Healthy Street in Seattle. Also called "play street", "living street", "low traffic neighborhood" in different parts of the world. People can drive through there only if they live on that street, or they're making deliveries. Pedestrians and bicycles and people playing outside are supposed to be the main use. They usually have some kind of sign or barrier at the entrances:
![960x0](https://user-images.githubusercontent.com/1664407/119198503-4b5c2200-ba3e-11eb-979a-aab9dcd33254.jpg)

We should probably depict these differently. The pink color isn't meaningful at all. We have the unzoomed view, shown above, and also the zoomed-in detail view like this:
![Screenshot from 2021-05-21 14-11-20](https://user-images.githubusercontent.com/1664407/119198590-6dee3b00-ba3e-11eb-98ac-caf0d702e560.png)

Maybe we could have a simple 2D top-down rendering of a barrier or a gatehouse? For the unzoomed view, I'm not sure what to do.

@trangrei

**Comment by trangrei** [comment]
What I am thinking first is that yellow usually signifies limited use or some light heads-up (oftentimes warning but that might seem too heavy here). I haven't read carefully into what the red, green and yellow tickmarks mean, but I'll look into it today (May 24th) and think of solutions to be consistent with our brand guidelines and avoid repetition of color and thus confusion.

**Comment by dabreegster** [comment]
Yellow is indeed a common "caution" sign color:
![No-Thru-Traffic-Sign-K-5987](https://user-images.githubusercontent.com/1664407/119379657-9bbcc500-bc74-11eb-9e92-76bd499c5e56.gif)

> I  haven't read carefully into what the red, green and yellow tickmarks mean

If you mean the real-life picture in the first post, I don't think those colors mean anything special; probably just some kind of reflective safety material.

We don't have to be limited to using color here, though maybe it is the simplest idea. OpenStreetMap puts these small grey ovals in the middle of the road to indicate some kind of private road:
![Screenshot from 2021-05-24 09-46-41](https://user-images.githubusercontent.com/1664407/119379997-01a94c80-bc75-11eb-96e5-ef0f1edc87be.png)
https://www.openstreetmap.org/#map=19/47.63041/-122.28684
Since we draw people moving on the road, this might not work out for us...

I searched google images for "ltn map" to get some more ideas and found:
![West-Ealing-South-LTN-Map-extra-wide-scaled](https://user-images.githubusercontent.com/1664407/119380108-23a2cf00-bc75-11eb-87ea-cd920c8266b1.jpg)
![Midhurst-road-closures](https://user-images.githubusercontent.com/1664407/119380112-243b6580-bc75-11eb-9de7-5dc197c792be.png)
Both of these put emphasis on the intersections instead, which is a neat idea -- the private neighborhood is guarded by a gatehouse, and the play streets are blocked by some kind of small barrier that let bikes through, but slow down cars. We could try that:
![Screenshot from 2021-05-24 09-51-23](https://user-images.githubusercontent.com/1664407/119380662-e0952b80-bc75-11eb-851d-67c9f2d256da.png)
But if we didn't color the streets pink, it wouldn't be too clear whether the north/south or east/west roads at those intersections had barriers...

We could try to draw the diverters:
![Screenshot from 2021-05-24 09-51-23](https://user-images.githubusercontent.com/1664407/119381884-2ce06b80-bc76-11eb-93f0-177c72075fc7.png)
I think this could work, even with the unzoomed people circles moving on top.

Zoomed in, maybe something similar is reasonable:
![Screenshot from 2021-05-24 09-59-04](https://user-images.githubusercontent.com/1664407/119382448-e0e1f680-bc76-11eb-90ac-0a589479b05a.png)
with some kind of icons to indicate bikes/foot traffic OK, no through-traffic for cars

Or even some attempt to physically show the planter boxes/signs often used...
![Screenshot from 2021-05-24 09-59-04](https://user-images.githubusercontent.com/1664407/119382550-0969f080-bc77-11eb-9d4e-74e8cf71ea6c.png)

These are all ideas focused on the "slow streets". For the private neighborhoods, I've also thought about calculating the land area surrounding the roads and just coloring all of that:
![Screenshot from 2021-05-24 10-02-56](https://user-images.githubusercontent.com/1664407/119382730-4c2bc880-bc77-11eb-9de7-7556650b893f.png)

All of these are just random ideas, I don't know what will be intuitive for people to understand and not clash with the other information we're trying to present. But we have the ability to get fancier than just a solid color, for sure

**Comment by trangrei** [comment]
![image](https://user-images.githubusercontent.com/10510160/119584870-67cdc680-bd7e-11eb-8c81-45a2fbf72f0f.jpeg)

Yea actually, using a lot of colors are sometimes not advisable, as it adds more complexity for the interface. I will team up with Yuwen more to come up with a solution for this.

**Comment by Robinlovelace** [comment]
Great to see this discussion. It's important to visualise these 'point' based interventions that prevent through traffic for motor traffic (not always for motorbikes but that's a different story) but allow people walking and cycling to pass. I think these types of intervention could be the single most effective way to enable more people to safely and comfortably walk and cycle. In terms of detail, I'm confident that A/B Street can do a better job than OSM: 

![image](https://user-images.githubusercontent.com/1825120/126350423-7c4b9d78-3d47-4844-b486-5827069a4da2.png)

Note, those planters actually look like this: 

![image](https://user-images.githubusercontent.com/1825120/126350658-5e572569-6644-477f-9739-d6ce5ea44332.png)

Currently this is how they are rendered in A/B Street 0.2.52 (source): there is no indication of the planters.

![image](https://user-images.githubusercontent.com/1825120/126351068-61654779-9a0a-45af-9d63-7f8f2aff9bd4.png)

This could partly be a result of the routing-focussed change to OSM that made the road an LTN, which simply added a small section of cycleway, guided by @mvl22 : https://www.openstreetmap.org/changeset/94519931

**Comment by Robinlovelace** [comment]
Of the sketches above the one that is most like a planter and most clearly provides filtered permeability is the most promising IMO but could clearly be improved from an aesthetic perspective.

![image](https://user-images.githubusercontent.com/1825120/126352074-51ccfaaf-118d-4c4b-a9d8-d6336b3827ff.png)

**Comment by mvl22** [comment]
Low-traffic neighbourhoods are not marked as such in OSM and almost certainly never will be. You cannot determine through-traffic status without performing a routability analysis.

Similarly, modal filter points are not marked in OSM as such, because the definition of a modal filter is not formalised. A modal filter could in some cases be a cycle gap in the middle of a residential street, but in other cases an almost identical gap will not a modal filter but in fact just a short cycle/walking route between two residential areas that traffic could never have used historically. Modal filters are often very non-obvious from the data.

We have been doing complex analysis to generate datasets for both modal filters and street status. A talk about this work can be seen at:
https://www.youtube.com/watch?v=LwmlR-0lypU&t=2737s
and the map will be available publicly soon. (We are currently in a beta phase of getting people to look over the data.)

**Comment by Robinlovelace** [comment]
> Low-traffic neighbourhoods are not marked as such in OSM and almost certainly never will be. 

Why not? It's great that the data on where they are will be made publicly available thanks to your analysis but I cannot see why you, or anyone in the OSM community, would be against tagging roads that are open for active travel but have no through access for cars.

**Comment by Robinlovelace** [comment]
> A talk about this work can be seen at:
> https://www.youtube.com/watch?v=LwmlR-0lypU&t=2737s

This is great to see, taking a watch now :+1:

**Comment by mvl22** [comment]
Because OSM already lets you tag what the legal status of the street is. From that, you can determine routability for any particular set of users.

Through-access is always something that needs context and interpretation. It depends what you are wanting to show.

For instance, York Street, Cambridge (shown here with a thick line) is not through-traffic in the sense of rat-running between main roads, because of the Hooper Street modal filter shown in black several streets to the south of it. But it **is** a through-traffic street for getting to other local streets. It could hypothetically also be a through-street to access a major showroom at the end of a dead-end street further up.

You can determine all these different scenarios by analysis of the raw street data, but by converse, the raw data can't define every possible combination of what level of through-trafficness a particular project might require.

![Screenshot 2021-07-20 at 17 22 53](https://user-images.githubusercontent.com/361423/126360512-43ad1972-032c-4587-8cc9-3a917d479dea.png)

**Comment by Robinlovelace** [comment]
> For instance, York Street, Cambridge (shown here with a thick line) is not through-traffic in the sense of rat-running between main roads, because of the Hooper Street modal filter shown in black several streets to the south of it. But it is a through-traffic street for getting to other local streets. It could hypothetically also be a through-street to access a major showroom at the end of a dead-end street further up.

Good to see a concrete example and I agree that whether or not that allows through traffic is open to interpretation (simple analysis would suggest yes it is).

However, I'm not sure that this is true for the majority of residential cases:

> Through-access is always something that needs context and interpretation. It depends what you are wanting to show.

Usually it's pretty clear and objective if there is no through traffic. That would be a narrower definition of LTNs (or no through traffic) but it would still be useful. I *think* it already has a tag on OSM but it seems this tag is little used: 

> Only when travelling to this element/area; i.e., local traffic only. NOTE: This restriction often only applies to certain modes of transportation (e.g., only to vehicles). Take care to use the right transport mode restriction; e.g., vehicle=destination when only vehicle traffic is restricted. 

Source: https://wiki.openstreetmap.org/wiki/Key:access#List_of_possible_values

**Comment by systemed** [comment]
`access=destination` records a legal restriction rather than a practical one - in the UK, it codifies the "Except for access" plate that you'll sometimes see underneath the flying motorcycles sign.

**Comment by Robinlovelace** [comment]
How about `vehicle=destination` @systemed ?

**Comment by Robinlovelace** [comment]
And in terms of the legal aspect, in many LTNs you can physically drive through planters, either by mounting the pavement or, as has unfortunately happened in a number of places, moving/damaging the planter. However, that would be illegal.

**Comment by mvl22** [comment]
> Usually it's pretty clear and objective if there is no through traffic.

I disagree. For what definition exactly?

Mill Road Cambridge currently has a bus gate forming a modal filter, which stops vast amounts of rat-running, from East Road to Perne Road. The eastern-most part of it still has through-traffic from East Road to the station. It all has through-traffic to access the side streets. But these are both at reasonable levels. How could objective data possibly represent the various scenarios here?

Our own analysis has a definition of rat-running, which is from one main road to another, broadly matching public perception. We will be defining this in the blog post we plan to publish shortly. But other people might have different requirements for classifying what exactly is a low traffic or no-through streets.


> Only when travelling to this element/area; i.e., local traffic only.

That matches a legal definition. But it still doesn't define whether a street is anything like a low-traffic neighbourhood. It could be a street that at the end has a vast Ikea shop with thousands of vehicles a day. That would be access only but still a very high-traffic street.

**Comment by Robinlovelace** [comment]
I guess in terms of LTN there is a balance and careful analysis is needed as you say in the talk. There are many residential streets that only allow access, however. That is perhaps a narrower category than LTN but there would be an overlap. Here are a couple of examples of residential streets with no legal through access for vehicles (both of which I've lived on coincidentally!):

https://osm.org/go/evjoxFU0v?layers=C

![image](https://user-images.githubusercontent.com/1825120/126364049-d2f30e90-1e50-42fc-b9ac-2a934a08c351.png)

And Riviera Gardens:

![image](https://user-images.githubusercontent.com/1825120/126364164-61e87b50-d371-4aad-9d4e-3c3183fb1be7.png)

These are places where no vehicle traffic can enter without leaving the other side. It's useful to have a broader definition also but in terms of tagging I still don't see why people would be opposed to saying that cars cannot pass through on OSM, e.g. with the `vehicle=destination` tag. Of course that would involve a lot of tagging activity which may not make it particularly relevant for this issue but it's a useful conversation to be having.

**Comment by Robinlovelace** [comment]
> I disagree. For what definition exactly?

Tentative definition: 'road that does not allow through traffic for vehicles'. Clearly there would be cases like a road leading to Ikea where there would be high traffic volumes. But if `highway=residential` I think that would mean that it's LTN-esque, no?

I agree that there are other types of LTN that allow through traffic but tagging the objectively defined ones, where you cannot legally (without driving on the pavement, over a field, or through a house), would seem like good thing, especially if there's already a tag for it.

**Comment by Robinlovelace** [comment]
Follow-on after conversation with @mvl22  on this: `vehicle=destination` also does not apply because there isn't usually a legal reason not to pass through in the UK. 'LTN' is not something that is defined in UK law and it's not an objective thing. Solution in the UK that may work in other places: use tags representing modal filters like `barrier=planter` and use a routing algorithm to find roads. Unfortunately this means more work on the A/B Street side @dabreegster but I'm sure Martin will be happy to share insight into their algorithmic definition of an LTN. In the meantime are there any quick wins, e.g. a road that has a modal filter at one end?

**Comment by dabreegster** [comment]
Thanks for all of the details on OSM and nuance about how access restrictions don't imply anything about the level of traffic. This issue was meant to focus on how to render these situations in A/B Street, so I'd like to swing the conversation back to that.

The closest pages on the OSM wiki I've found to discussing tagging are https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street, https://wiki.openstreetmap.org/wiki/Key:barrier#Linear_barriers_or_access_control_on_highways_.28e.g._along_or_for_blocking_a_path_or_road.29, https://wiki.openstreetmap.org/wiki/Key:access#List_of_possible_values. Because this is such a nuanced topic, I think it'd be massively helpful both for mappers and data consumers to have a wiki page summarizing the different tagging styles, recommendations, and caveats. @matkoniecz or anybody else, would you be interested in volunteering to start such a page?

Robin, I'll eventually get around to recognizing more of the OSM tagging schemas in A/B Street and doing the reachability analysis. And in the meantime, I can make some quick changes to iterate on situations in Leeds. But let's please move that to a different issue and focus on visual design here.

**Comment by matkoniecz** [comment]
> Similarly, modal filter points are not marked in OSM as such, because the definition of a modal filter is not formalised.

Note that OSM does not have tag for "modal filter" but anything used to create modal filter is taggable. So OSM mapper will not tag "modal filter" - the will mark bollard/short section of cycleway instead road, planter blocking through car traffic etc.

**Comment by matkoniecz** [comment]
> I think it'd be massively helpful both for mappers and data consumers to have a wiki page summarizing the different tagging styles, recommendations, and caveats.

What kind of info is missing and not presented at pages you linked? For examples https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street discusses already situation - including whether "stay healthy street" does qualify as `highway=living_street` or not.

https://wiki.openstreetmap.org/wiki/Key:barrier also seems relatively clear - at least to me

**Comment by matkoniecz** [comment]
> Visualizing low-traffic neighborhoods and gated communities

> This issue was meant to focus on how to render these situations in A/B Street, so I'd like to swing the conversation back to that.

What about simply using different colors? Some greenish for living street or similar and purpleish/red outline/current styling for gated community?

**Comment by Robinlovelace** [comment]
Agreed, it went a bit off topic after this post: https://github.com/a-b-street/abstreet/issues/660#issuecomment-883487134

Suggestion: you could mark some of these posts as [off topic](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments) but it's an important conversation. Back on topic, I think highlighting the modal filters already in OSM is a quick win, visualising LTNs first requires a definition of an LTN which I think Martin's work at https://ltns.cyclestreets.net goes a long way towards. See [here](https://lists.openstreetmap.org/pipermail/talk-gb/2021-June/027185.html) for password to use the site and even wordier discussion of this topic.

**Comment by dabreegster** [comment]
> What kind of info is missing and not presented at pages you linked?

The individual pages do a good job of detailing how to use each tag. But if somebody comes along and says "how do I tag an LTN?", they have to look around and find the page describing barriers, and also wonder about access restrictions and `highway` classification. I'm suggesting a page dedicated to the topic of LTNs that points to these pages and gives guidance, perhaps with region-specific details. Ideally some example pictures and a summary of tags, like https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/Radwege#Tagging-Beispiele. Martin's post at https://lists.openstreetmap.org/pipermail/talk-gb/2021-June/027185.html does a great job of explaining different types of physical features (and the corresponding tagging) related to the concept of LTNs.

**Comment by Robinlovelace** [comment]
I've just created an OSM Wiki account and have made minor edits plus created this page on 'planters', one of the most popular and cost effective modal filters for creating LTNs: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dplanter

**Comment by matkoniecz** [comment]
> https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dplanter

Good find! I added some technical touches (infobox template).

If someone wants page for modal filters linked there also may be worth creating.

**Comment by dabreegster** [comment]
Thanks for starting the wiki!

Back to visualization ideas, here's an attempt to compute and color the land surrounding the LTN / private neighborhood / access-restricted area. (I realize these're different and should be rendered distinctly, but not there yet.) It takes all of the buildings along private roads and forms a convex hull. Sometimes it looks half-decent, but convex hull isn't the right algorithm for all cases. If this kind of idea looks useful, I can put effort into fixing it up.
![Screenshot from 2021-07-20 15-56-28](https://user-images.githubusercontent.com/1664407/126405774-3d2cdc1f-f1eb-4735-94f8-2aabab457c7f.png)
![Screenshot from 2021-07-20 15-56-05](https://user-images.githubusercontent.com/1664407/126405776-f1149460-1c0d-4760-8513-892b8a35fab5.png)
![Screenshot from 2021-07-20 15-55-41](https://user-images.githubusercontent.com/1664407/126405778-043c3e70-2c7b-4432-aa54-76f7cd7bf1bf.png)
![Screenshot from 2021-07-20 15-55-32](https://user-images.githubusercontent.com/1664407/126405780-ef5811f8-ea72-47ca-acff-730b65ee0207.png)
![Screenshot from 2021-07-20 15-55-25](https://user-images.githubusercontent.com/1664407/126405782-ea0af6d9-83f4-4496-88c6-0cf8742abe94.png)

**Comment by dabreegster** [comment]
And just drawing the boundary of that convex hull, meant to evoke the idea of a fence/barrier. I'm not a fan, just throwing it out there:
![Screenshot from 2021-07-20 16-02-01](https://user-images.githubusercontent.com/1664407/126406037-86d265df-8840-4159-801d-492154b2ffea.png)
![Screenshot from 2021-07-20 16-01-57](https://user-images.githubusercontent.com/1664407/126406039-5cf98dea-c9c3-4b34-8811-edd49979c8df.png)

**Comment by dabreegster** [comment]
And trying some different colors. Unzoomed, we have to not clash with the 4 agent circle colors. Also need to consider night mode.
![Screenshot from 2021-07-20 16-06-18](https://user-images.githubusercontent.com/1664407/126406324-0cb57c17-23c0-41bd-b539-5511afc65d39.png)
![Screenshot from 2021-07-20 16-06-12](https://user-images.githubusercontent.com/1664407/126406326-df766359-7bd0-4f08-a001-a57b7769daef.png)
![Screenshot from 2021-07-20 16-05-32](https://user-images.githubusercontent.com/1664407/126406332-656ffec9-3669-44b0-bd74-632325539f9f.png)
![Screenshot from 2021-07-20 16-05-25](https://user-images.githubusercontent.com/1664407/126406333-e58b63da-6f65-4f87-ad29-326935f20728.png)

**Comment by Robinlovelace** [comment]
Realise now that *this* issue is where this image should be posted: 

![image](https://user-images.githubusercontent.com/1825120/126716989-dfb9e78e-56c2-4ffa-aa3b-235b0cd1b16a.png)

I think that visualising barriers to cars, which transform roads from unpleasant dangerous places to sociable safe places, is important, the examples above make good progress in that direction. There is a question of how to define a street as an LTN or not, after discussion with Martin (who has been tagged enough in these kinds of discussion, thanks for all the input!) and I think the definition of roads with little or no through traffic, based on routing between junctions on major roads, is a good starting point.

**Comment by Robinlovelace** [comment]
Here's a bit of visual inspiration about what is needed: I think making the newly safe roads clearly different is vital for sharing the message. This tweet sums up the message well: https://twitter.com/adamtranter/status/1418475654627139587

![image](https://user-images.githubusercontent.com/1825120/126762831-9b941b1b-26e7-4166-99fd-64409358b0c0.png)

Note the green, with associations of safety, plants (e.g. in planters) and an outdoor feel.

**Comment by dabreegster** [comment]
Before this gets lost to history: https://github.com/a-b-street/abstreet/pull/715#issuecomment-887093583 bunch of ideas for zoomed-in rendering

**Comment by Robinlovelace** [comment]
Nice illustration of a private sign in #715. I think something like this but filtered would be a pretty quick win at a time when these things are going in and people are increasingly interested in redesigning streets using them. Modified version of sketch from @westnordost below.

LTN + planters is my 1st take, using the new LTN svg icon, on colouring for filtered permeability and change in colour of tarmac (to green in this case when zoomed in):

![image](https://user-images.githubusercontent.com/1825120/136105805-a8373380-9960-41a7-b5cc-a7f52e4505d7.png)

**Comment by trangeriale** [comment]
Hi all,

I discussed with Dustin some animation idea and the planter is definitely a great place to start. After observing more LTN/walking street with planters, I think it serves well as an annotation for a walking/limited traffic neighborhood.

One question I would like to ask is about the use case. I talked to Dustin about the use of the LTN visualization tool to prevent rat-run, but before that, I read this documentation by @michaelkirk and I was wondering if the use case/purpose of LTN in these two cases are complementary to each other? (allowing for biking/walking through Broadmoor and prevent rat-runs to keep a peace of mind for the biker and walkers?)

https://a-b-street.github.io/docs/proposals/broadmoor.html

**Comment by dabreegster** [comment]
> allowing for biking/walking through Broadmoor and prevent rat-runs to keep a peace of mind for the biker and walkers?

There are similarities, because both restrict _who_ can access some space. I originally lumped these two ideas together because some of the rendering seems like it could serve both purposes. But I think we should focus on LTNs in the rat-running sense. There's really only one gated/private neighborhood that we know of that's interesting to study/write about -- and we already have done that. But there's dozens of places actively looking into adding modal filters and creating LTNs **right now**, and even more looking at a more dramatic version ([superblocks](https://www.bloomberg.com/news/articles/2020-11-11/barcelona-s-new-car-free-superblock-will-be-big)). So I'd vote for forgetting about Broadmoor / the gated community case and focusing the efforts of this new tool on creating car-free or car-light **public** spaces.

**Comment by Robinlovelace** [comment]
> And as @Robinlovelace mentioned the planter is also promising towards visualizing such areas, so can we possibly incorporate these ideas in mind for our design?

Big thumbs up from me, I think the motivations for this are well documented in the recent comments above. Thanks for looking into it and look forward to seeing what emerges from this discussion, very happy to comment on any subsequent ideas/designs/implementations!

**Comment by trangeriale** [comment]
Hi Robin, I think showing the roads in green after the planters are added to the map is an amazing idea, as it clearly shows the "green effect" (but we can also use it to annotate a street that has **absolutely no rat runs** after those planters are included)

## mainscreen of rat run viz tool
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/10510160/136176928-c21f0afe-f55b-4488-9d3d-8caebdc6a24f.png">

## toggle mode to see all rat runs
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/10510160/136178673-a17a69a8-ff8c-46f9-a7ca-0c9bd4bf98e0.png">


This is a very quick static prototype I have of the possible inclusion of
1. a minimalistic symbol for planter 
2. feature to toggle showing all rat runs (my initial thought is to make the rat run roads opaque in this mode, so the roads with the most rat-runs going through would be the reddest, but it didn't seem too obvious on Figma, compared to opaque dot plots where each dot only partially overlaps one another)
3. neighborhood name included
4. play button to start simulation after planters are added

I think the behaviors of what happen when users play the simulation is what to be worked on. One question I have from the engineering end is: Can users play the simulation and add the planters at the same time, or would the animation transition be too abrupt?

I would love to tag you in this Figma file but couldn't find your email, but maybe @dabreegster could add you to the file!

**Comment by mvl22** [comment]
Most of the bits of those streets you marked in green are still potential rat-runs though, given that there are spurs for smaller streets shown coming off them. Only the very edge where they join the main road isn't.

Are you planning to perform a full routability analysis? Modal filters do or don't have significant changes further up the street network obviously.

https://www.cyclestreets.org/news/2021/07/25/mapping-ltns/

**Comment by trangeriale** [comment]
Hi Martin, thanks for joining our conversation! So most of these are prototypes for visual purposes so they don't account for precision of the analysis. This is mainly for interaction design/what behavior will result in after users click or perform certain actions.

**Comment by matkoniecz** [comment]
> rat run viz tool

What about marking places where access become completely impossible? Unless someone wants to pedestrianize street it is unwanted.

**Comment by trangeriale** [comment]
Hi, please refer to our documents above (one of our goals is to make the streets friendlier to pedestrians and bikers).

**Comment by Robinlovelace** [comment]
And in terms of visualisation, I really really like the design work illustrated in this comment: https://github.com/a-b-street/abstreet/issues/660#issuecomment-935852448 

I guess that seeing all 'rat runs' may be more useful than seeing one-at-a-time. That could also make the UI simpler. But I really like the concept and different colored roads depending on how save they are for walking/cycling/wheeling/playing which is basically the same as how much through traffic there is (none in an LTN).

**Comment by dabreegster** [comment]
I started #770 for more general discussion. I'm enjoying the conversation and learning lots, but yeah, let's stay focused in this issue on rendering/viz please

**Comment by dabreegster** [comment]
> map svg credit

@trangeriale, I think the color scheme you've chosen for the different LTN-related elements works really well on this image. We currently use a different scheme for the unzoomed view. Do you think we should switch to something closer to this example for the LTN tool? It should be hopefully be simple to try it in https://github.com/a-b-street/abstreet/blob/master/map_gui/src/colors.rs... figuring out how all of this works in the zoomed-in view is another matter, though. I like Robin's transparent green tarmac layer idea for that.

**Comment by dabreegster** [comment]
Lots of awesome discussion here, but nothing actionable anymore. #856 has some ideas for improving what we've got further
