### ISSUE TITLE
Stop sign color in dark mode

### ISSUE THREAD

**Issue by muzlee1113** [a-b-street/abstreet#667]
The stop sign color is too dark.
Change it to `#A32015`

**Comment by dabreegster** [comment]
Thanks, fixed! I think Michael actually adjusted this a while back.
![Screenshot from 2021-06-08 07-28-22](https://user-images.githubusercontent.com/1664407/121203694-28e24b00-c82b-11eb-9e2b-4fe88f19716c.png)
https://github.com/a-b-street/abstreet/blob/ecce96fd75cd0ec7ab6d5791916b7a79a73be335/map_gui/src/colors.rs#L484
