### ISSUE TITLE
Crash when changing trip mode

### ISSUE THREAD

**Issue by dylanwinn** [a-b-street/abstreet#674]
To replicate:
1. start game
2. sandbox
3. edit traffic patterns
4. change trip mode
5. apply
6. crash

[output.txt](https://github.com/a-b-street/abstreet/files/6633841/output.txt)

**Comment by dabreegster** [comment]
Thanks for reporting with a clear repro! It's fixed if you're compiling from the latest git source. The fix will also be in this Sunday's build.
