### ISSUE TITLE
Crash when changing road speed limit during tutorial

### ISSUE THREAD

**Issue by iulivs** [a-b-street/abstreet#685]
Tried to complete the "edit a road" section during the tutorial, tried changing a speed limit to 70 mph and game crashed.
[output.txt](https://github.com/a-b-street/abstreet/files/6718222/output.txt)
("edits_during_crash.json", couldnt upload thru github) https://www.mediafire.com/file/aq8jvd647fhfzr7/edits_during_crash.json/file

**Comment by dabreegster** [comment]
Thanks for reporting, and sorry it took so long to get to this! It's fixed now, and will be in the next downloadable release / web version on Sunday.

No comment on the strategy of making a tiny residential road 70mph...
