### ISSUE TITLE
empty space between crossing and road

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#696]
http://abstreet.s3-website.us-east-2.amazonaws.com/0.2.50/osm_viewer.html?system/pl/krakow/maps/center.bin&--cam=19.50/50.06555/19.92475

Crossing shape sort of makes sense, but gaps are weird
![screen03](https://user-images.githubusercontent.com/899988/125210706-d2d94b00-e2a1-11eb-8906-e3d2d9d90815.png)

**Comment by dabreegster** [comment]
This is near https://www.openstreetmap.org/node/2106196385. There are some inner ways marked as junctions:
![Screenshot from 2021-07-11 15-55-35](https://user-images.githubusercontent.com/1664407/125212188-8883aa00-e260-11eb-9636-70dbbbeab9e2.png)
So this is the intersection consolidation algorithm absolutely blowing up.

https://www.openstreetmap.org/way/21931182 is the challenge here -- it's going to force a single intersection polygon to be huge and cut in at strange angles. I'm still focusing on simpler cases in #654, but I'll take a stab at this one eventually.

**Comment by matkoniecz** [comment]
One bad part is that (as seen on aerial) part of junction is just road split and cars can stop there. But even with current data the output geometry is not what should be produced.

Still, maybe it should be also edited in OSM.

**Comment by dabreegster** [comment]
Closing this since it's not super actionable. Improving geometry no matter what's in OSM is still occasional work, some progress in #654
