### ISSUE TITLE
Improved queuing model for cycling

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstreet#700]
In many simulations there is little cycle traffic so it doesn't matter than bikes queue in the same way cars do. When simulating scenarios of high cycling uptake, or cities like Amsterdam, the current car-like queuing model for cycling will cause issues. This is how it looks currently, in Leeds under a simple scenario of cycling uptake:

![image](https://user-images.githubusercontent.com/1825120/125590417-19e65c21-2d69-47a2-9eec-826d37155890.png)

Source: http://abstreet.s3-website.us-east-2.amazonaws.com/0.2.50/abstreet.html?system/gb/leeds/scenarios/north/background.bin&--cam=20.94/53.81192/-1.53442

Proposal: make changes so that it can look more like this: 

![image](https://user-images.githubusercontent.com/1825120/125590622-1faef0d9-5d3d-4e22-b7ba-f0b79db51268.png)

Or this - that suggests bicycles ~4 abreast per road is doable when cycling. On that note 2 or 3 abreast is also doable on a normal width road.

![image](https://user-images.githubusercontent.com/1825120/125590819-fd8293fe-249c-42b3-8fb2-68f97b8bd41b.png)

Sources: https://grist.org/living/1-in-4-rush-hour-vehicles-in-london-is-a-bicycle/ and my tweet thread that motivated this issue: https://twitter.com/robinlovelace/status/1415221101932724226

**Comment by dabreegster** [comment]
I'll dedupe this issue with #187 -- y'all even used the same Amsterdam picture! Adding some notes there.
