### ISSUE TITLE
looking for a blog post

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#701]
https://github.com/a-b-street/abstreet/releases/tag/v0.2.51 mentions blog post but not linking it (maybe it is not yet posted?)

blog is not mentioned at https://github.com/a-b-street/abstreet (maybe it is mentioned in some blog rather than own A/B Street blog)

https://github.com/a-b-street/abstreet/search?q=blog is not finding anything relevant

The same for https://duckduckgo.com/?q=a%2Fb+street+blog&t=ffab&ia=web and https://duckduckgo.com/?q=a%2Fb+street+blog+!g&t=ffab&ia=web

**Comment by dabreegster** [comment]
https://a-b-street.github.io/docs//proposals/broadmoor.html

Twitter conversation: https://twitter.com/CarlinoDustin/status/1415410453044289538

**Comment by matkoniecz** [comment]
Thanks!

Thanks, very interesting! I bet that main issue is that whole issue is that essence of gated community is ignoring general public. So likely government would act and force them to allow passage to change anything. 

My actionable feedback is that https://a-b-street.github.io/docs//proposals/broadmoor.html#trip-durations graph is not really obvious and would maybe benefit from some explanation how to interpret it.
