### ISSUE TITLE
Iterate on "apply changes to multiple roads/lanes"

### ISSUE THREAD

**Issue by muzlee1113** [a-b-street/abstreet#718]
1. The colors of the edited road/lane and selected ones (dark blue now👇) are not very obvious in dark mode. 
![image](https://user-images.githubusercontent.com/44761143/127030393-4c59ac58-ba7b-41de-a8d7-66eb8da07c65.png)
Suggestion: try using the theme color orange #EE702E which I think might work better on both modes. 
Also, I would add a tooltip on the edited road/lane just to make it clearer.
![image](https://user-images.githubusercontent.com/44761143/127032930-0e409e6e-fe8a-4521-bb47-442dab9ca095.png)

2. It is easy to lose the context of the changes, losing check of which lane/road was edited especially in the night mode.
Suggestion: adding relocation functionality on both editor and multi-road editor
![image](https://user-images.githubusercontent.com/44761143/127032288-81d1b9d4-0f1a-47f8-9633-44174c5ab519.png)
[Figma Link](https://www.figma.com/file/aYSWQei1XjAe2HvjtmhQsd/?node-id=102%3A1856)

**Comment by dabreegster** [comment]
Thanks, both changes done! I'm redeploying the web app for a quick preview, but I'm on the slow laptop...

![Screenshot from 2021-07-26 13-00-58](https://user-images.githubusercontent.com/1664407/127051339-9c7887e5-6467-4e5a-95b5-bfc436d3bf50.png)
![Screenshot from 2021-07-26 13-00-14](https://user-images.githubusercontent.com/1664407/127051341-66248e2c-22bd-4eef-a581-cfb2c1bb524d.png)
`ab_orange_1` is maybe a bit too close to the current arterial road color in day mode, but it's still distinguishable. And I suspect those colors might be shifting soon anyway.

**Comment by dabreegster** [comment]
Changes live at http://abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&system/us/phoenix/maps/tempe.bin&--cam=19.58/33.42743/-111.92628

I'll close this, since both issues you reported are now fixed, but we can reopen if we need to adjust more
