### ISSUE TITLE
Revamp command-line tools

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#745]
@Robinlovelace pointed out that people using the binary release cannot [import JSON scenario data](https://a-b-street.github.io/docs/tech/dev/formats/scenarios.html#tools). They must install Rust and compile everything themselves. This is because `import_traffic` isn't one of the tools included in the binary release: https://github.com/a-b-street/abstreet/blob/c5671557defbd80ce749b8fa7faf7c166b3d23dd/release/build.sh#L46

In the short term, we could just add it there. But this could be an opportunity to make some improvements. The .zip releases are 70-90MB today, depending on the platform. Previously we did work to remove most map data from them by default, and defer downloading it. Now the space comes from all of the large executable files. The main apps -- the game, 15m viewer, Santa, OSM viewer, parking mapper -- were once all squished together in a single crate and binary, but we split them up once we had a better sense of the differing "product" goals. The .zip also includes 6 different tools, mostly used to import maps. Adding another tool here would increase the .zip size a bit more.

An idea in the back of my mind that might be more relevant now is to instead consolidate all of these different import tools into a single executable. This would definitely save on .zip file size, since all the tools share most dependencies. But it's also a chance / forcing function to design a better CLI experience -- using some proper Rust crate for flag parsing and `--help` generation. (I think @michaelkirk mentioned this desire recently.)

To be more clear, https://github.com/a-b-street/abstreet/tree/master/importer/src/bin has a bunch of one-off tools today. I think refactoring these to become libraries, then exposing each one as a subcommand of a single importing-related multi-tool could be nice.

**Comment by dabreegster** [comment]
- [ ] Update all of the `abstr` docs. Hopefully lots of stuff there gets simpler.
- [ ] Split the `importer` into a few different subcommands and properly use `structopt` for them

**Comment by Robinlovelace** [comment]
Great to see progress on this, amazing work! I'm up for helping out with the docs and testing.

**Comment by michaelkirk** [comment]
Yeah, great work!

**Comment by dabreegster** [comment]
This was only open to consider using Path/PathBuf properly. I still think a better type would be great. https://crates.io/crates/camino is one option.
