### ISSUE TITLE
Dragging the view when a tutorial trigger happens freezes the UI completely [browser]

### ISSUE THREAD

**Issue by jenniNelson** [a-b-street/abstreet#754]
First time trying the game out, trying the web browser while the dev version builds.
During the tutorial in the "time control" section if you're dragging the camera around when it hits 5:00pm the whole UI freezes and the mouse pointer gets stuck as a dragging cursor. No way out except to reload the game.
![image](https://user-images.githubusercontent.com/26044614/133730228-c0a47fb7-3cd9-4524-85ff-550f1782b9f2.png)

**Comment by dabreegster** [comment]
Thanks for reporting! I can reproduce this on the native version too. This bug is actually everywhere -- in sandbox mode or anywhere you can interact with the map, pressing escape or another key to open up a panel while dragging gets things stuck. I'll find a fix tomorrow.

**Comment by dabreegster** [comment]
I fixed the immediate issue, but there's still a weird edge case left, noted in the comments in that commit. I don't think that should cause many problems, so I'll close this issue for now. Thanks for finding this!
