### ISSUE TITLE
Mismatched types error when using importer

### ISSUE THREAD

**Issue by lorenzschmid** [a-b-street/abstreet#755]
I do not know rust so it might very well be that I made a mistake in my setup. I tried to use the importer script to import a new city when I stumbled upon the following error:

```bash
$ ./import.sh 
   Compiling gdal v0.8.0
error[E0308]: mismatched types
  --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/gdal-0.8.0/src/vector/geometry.rs:99:17
   |
99 |                 wkb.as_ptr() as *const std::ffi::c_void,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
   |
   = note: expected raw pointer `*mut u8`
              found raw pointer `*const c_void`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `gdal` due to previous error
```

Any hints on what I do wrong or might there be an other issue?

**Comment by dabreegster** [comment]
https://a-b-street.github.io/docs//tech/dev/index.html#dependencies
I think your version of the GDAL library is probably old and incompatible with the Rust library. I remember getting this problem when I was on Ubuntu 18.04.

Simple fix is to delete `--features importer/scenarios` from `import.sh`. This will prevent regenerating one particular part of Seattle scenarios that needs GDAL, but there's no need to do that piece anyway.

**Comment by lorenzschmid** [comment]
Thanks a lot for the quick answer. That did indeed the trick, awesome! Thank you!
