### ISSUE TITLE
Alt-tab registers as pressing tab

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#761]
Alt-tab on most platforms switches between windows. If you open the city picker UI, then alt tab to another window, the UI registers the tab key and opens up the search tool.

https://github.com/a-b-street/abstreet/blob/f17f4c27312c86ade9d99de5a8e66cc6f6d44db6/widgetry/src/runner.rs#L375
Can we skip most events if the window isn't the active focus?

**Comment by abdulroufsidhu** [comment]
I am trying to reproduce the error can you please elaborate, e.g step by step guide to reproduce.

**Comment by abdulroufsidhu** [comment]
I am trying to reproduce the error can you please elaborate, e.g step by step guide to reproduce.
I am interested in fixing it.

**Comment by dabreegster** [comment]
Hi! To repro:

1) Open the OSM viewer tool (http://play.abstreet.org/0.3.43/osm_viewer.html or `osm_viewer` in the .zip release or `cd apps/osm_viewer; cargo run` from git
2) Press tab. You should see the business search widget expand or collapse
3) Press alt+tab to switch to another window
4) Switch back to the OSM viewer by clicking the window (or anything besides alt+tab). You'll see that it picked up the tab

`widgetry/src/event.rs` is where `winit` events turn into widgetry ones, tab included. The fix probably involves using winit's API differently, like maybe figuring out if our window is the current focused/active one when we hear a keypress

**Comment by dabreegster** [comment]
I'll also note that `widgetry/Cargo.toml` is using winit 0.27, in case that makes looking up winit's API confusing. There may have been relevant [changes](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md) since then. I haven't upgraded to modern winit because it requires upgrading `glutin`, and the API for that changed very dramatically recently and it's more work than I can invest so far
