### ISSUE TITLE
Missing link to roadmap in README

### ISSUE THREAD

**Issue by d2weber** [a-b-street/abstreet#796]
https://github.com/a-b-street/abstreet/blob/324ef84b3cf6640e77b086853971fb1c56c39283/README.md?plain=1#L46

**Comment by d2weber** [comment]
The refered link https://a-b-street.github.io/docs/project/roadmap.html is nonexistent.

**Comment by dabreegster** [comment]
Good catch, thanks! The github homepage is in dire need of an overhaul, but at least this link is fixed.
