### ISSUE TITLE
Displaced street labels

### ISSUE THREAD

**Issue by d2weber** [a-b-street/abstreet#799]
Sometimes the street labels are displaced, as it can be seen in this example in Seattle Downtown:
![image](https://user-images.githubusercontent.com/29163905/140654757-ae5ff7ac-dd11-4186-9078-579af81416fd.png)
The background of the label is centered as normal, but the text has an offset.
I am using Ubuntu 20.04 and a built from 6b766ea75.

**Comment by dabreegster** [comment]
I've definitely seen this sometimes. I know there are odd cases when the road's yellow center line doesn't match up with the physical center of the road, like when there's 4 lanes one direction and only 1 the other. But this case looks symmetric, so not sure why it's failing.

https://github.com/a-b-street/abstreet/blob/6b766ea750a6f105f713bfdf0e50988394682434/map_gui/src/render/road.rs#L100
`let (pt, angle) = r.center_pts.must_dist_along(r.length() / 2.0);` finds the middle of the polyline representing the road's physical center line. The text is then centered on that point. I can dig into this... hopefully this week.

**Comment by dabreegster** [comment]
Ah, possibly centering before rotating is causing some problems. Where is 17th in the downtown map just a narrow alley like that -- what's the cross street, so I can check what happens here?

The issue with the road center line and uneven lanes:
![Screenshot from 2021-11-07 09-29-27](https://user-images.githubusercontent.com/1664407/140655340-285c28ef-337a-48d8-94ed-bbac39583d09.png)

**Comment by d2weber** [comment]
> Where is 17th in the downtown map

Its on the bottom right:

![Screenshot from 2021-11-07 20-51-40](https://user-images.githubusercontent.com/29163905/140659715-4435020f-44fd-4f40-a98a-c1280d1cfede.png)

To get a better understanding of `pt` and `polyline` I made a quick plot of the polyline and the label position as calculated by `must_dist_along`. It seems that the position is correct.

![image](https://user-images.githubusercontent.com/29163905/140660354-7b0505a4-b6ae-460c-b171-cb4d4ad1e65d.png)

For this purpose I made a custom map with these boundaries to write out the coordinates:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -122.31053352355957,
              47.60612687571865
            ],
            [
              -122.30999708175658,
              47.60612687571865
            ],
            [
              -122.30999708175658,
              47.6068014076014
            ],
            [
              -122.31053352355957,
              47.6068014076014
            ],
            [
              -122.31053352355957,
              47.60612687571865
            ]
          ]
        ]
      }
    }
  ]
}
```

**Comment by d2weber** [comment]
> possibly centering before rotating is causing some problems

It should not, as the polygons are rotated around the center.

I noticed that the horizontal position of the label changes, depending on the text on the label. For example, if there are only lowercase letters, it moves way to much to the right. So I suspect that handling of the boundaries of the textspan might be problematic.

**Comment by dabreegster** [comment]
On the `label_centering` branch, I made a tiny change: https://github.com/a-b-street/abstreet/commit/5d46e2d0badbfe77d41c95e2e6c1779fe42245c1
I don't remember the details of how we transform text into polygons (https://github.com/a-b-street/abstreet/blob/master/widgetry/src/text.rs and then through `usvg` and `lyon`... complex pipeline), but it looks like rotating around the center of the entire text batch, rather than each polygon individually, helps. https://github.com/a-b-street/abstreet/blob/4717c3c8f7072cd0efc6c49403f724b95f8738fe/widgetry/src/geom/mod.rs#L209

Now it looks like this:
![Screenshot from 2021-11-07 13-11-08](https://user-images.githubusercontent.com/1664407/140662010-3d73f6d8-08a0-46eb-8189-ae376e540f24.png)

**Comment by d2weber** [comment]
I didn't quite understand the text rendering, for example, where does the magic `0.2` come from.. https://github.com/a-b-street/abstreet/blob/4717c3c8f7072cd0efc6c49403f724b95f8738fe/widgetry/src/text.rs#L352

But yes, with your fix it looks much better. Great!

**Comment by dabreegster** [comment]
Oh don't worry, I probably don't understand it either at this point. :\

I'll try out the fix more thoroughly and merge the commit. If you spot any places where the labeling looks strange, let me know. Thanks!

**Comment by d2weber** [comment]
Okay, thank you!
