### ISSUE TITLE
Glitchy Geometry for road

### ISSUE THREAD

**Issue by Zaneo** [a-b-street/abstreet#833]
![image](https://user-images.githubusercontent.com/295949/148385939-6581d3bf-8095-42ca-978e-7fec09e2ee59.png)

Way: https://www.openstreetmap.org/way/114559247

I do not expect any action on this, I just wanted to point out a case where there was something funny going on.

**Comment by dabreegster** [comment]
To repro easily, geojson is:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              139.71793055534363,
              35.58628785038091
            ],
            [
              139.7271680831909,
              35.58628785038091
            ],
            [
              139.7271680831909,
              35.59249116981333
            ],
            [
              139.71793055534363,
              35.59249116981333
            ],
            [
              139.71793055534363,
              35.58628785038091
            ]
          ]
        ]
      }
    }
  ]
}
```

Look for lane 1763.

Something very funny is going on with OSM here... try clicking the intersections at either end and jumping to the OSM nodes. I get https://www.openstreetmap.org/node/1297431637#map=19/35.58856/139.72453 and https://www.openstreetmap.org/node/2071014569#map=19/35.58835/139.72473, but that second one isn't a member of the way

**Comment by dabreegster** [comment]
Actually wait, this is the classic problem with curved roads that have lots of points:
![Screenshot from 2022-01-06 13-46-50](https://user-images.githubusercontent.com/1664407/148392377-77e6bdac-e588-4be6-8517-64d04d5096de.png)

I manually removed some of the points with the `RawMap` editor and the problem cleared up. I literally made some changesets the other day to fix a similar problem elsewhere. @michaelkirk suggested using https://docs.rs/geo/latest/geo/algorithm/simplify/trait.Simplify.html to do this automatically, which would be way less of a hassle.

I'll try this out!

**Comment by dabreegster** [comment]
![Screenshot from 2022-01-06 16-03-14](https://user-images.githubusercontent.com/1664407/148412287-787fffac-63c8-4ed2-ad57-866261f99e84.png)
It's looking like an easy win! I'll regenerate all maps with this line simplification, then push through the change

**Comment by dabreegster** [comment]
Another example of a fix from the screenshot test in Kennington, London. Before:
![Screenshot from 2022-01-06 17-24-01](https://user-images.githubusercontent.com/1664407/148424500-8c8b671a-3da1-43e8-b907-53ed359f8272.png)
After:
![Screenshot from 2022-01-06 17-24-03](https://user-images.githubusercontent.com/1664407/148424513-7ec01ebc-5d78-4b68-91e9-2a663d5dd4b7.png)
The fix will be merged momentarily, in next Sunday's build, or you can try it asap if you're building from source.

Thanks for raising this issue and urging a proper fix!
