### ISSUE TITLE
GET /map/get-all-geometry API, but export geojson for other cities?

### ISSUE THREAD

**Issue by trivisonno** [a-b-street/abstreet#838]
In 5.1.2 of the docs, you write about the get-all-geometry function to dump all of the geojson for roads and intersections, and that works fine. I'm wondering how I would load some different map to use this function.

Right now I just run:
`cargo run --release --bin headless -- --port=1234`
but this just runs the default Seattle map. Is there some variable I can pass that would allow me to use this with other cities?

Working on replicating a Traffic Calming map that Austin, TX put together, but for Cleveland, OH. (https://austin.maps.arcgis.com/apps/instant/interactivelegend/index.html?appid=0c340a6640f349ceb99538525f525651) Interested to experiment with your geometries!

**Comment by dabreegster** [comment]
There's `/sim/load` for changing the current map and scenario (travel demand model), but no way to just change the map. So I think the simplest thing is to first generate a dummy scenario:

```
cargo run --release --bin cli -- random-scenario --map data/system/zz/oneshot/maps/cleveland.bin --rng-seed 42 --scenario-name tmp
```

Then you can run the headless server, and do

```
curl http://localhost:1234/sim/load -d '{ "scenario": "data/system/zz/oneshot/scenarios/cleveland/tmp.bin", "modifiers": [], "edits": null }' -X POST`
```

to swap the map.

I'm actually looking into splitting out some pieces of A/B Street into more self-contained libraries, like [osm2lanes](https://github.com/a-b-street/osm2lanes), and an "osm2polygons" is another idea. It would likely output this same GeoJSON -- one polygon feature per road segment and intersection. If there's any other info you'd like to see in this export, let me know, and I'll see about including it. Thanks!

**Comment by trivisonno** [comment]
Perfect!

**Comment by dabreegster** [comment]
Keep me posted on the traffic calming map -- I'd be curious to see new dataviz based on maps with more detailed road geometry. And thanks for the sponsorship!

**Comment by trivisonno** [comment]
We built a first version of our traffic calming map using state-compiled centerlines, but I'd like to switch over to OSM data to enable our work to scale easier to other cities and regions and also because it can be a source of greater detail of the roadway's geometric deisgn. Here's a description of how we made the first version of our map, so you can get a sense of where we've been and what we're working towards: https://apricot-comfort-2d3.notion.site/Making-Cleveland-s-Traffic-Calming-Program-Scoring-map-ea98d1211b95467ba37ba04df86eecc8

Your write-up of intersection geometry challenges really resonated with me--there's so many edge cases!

**Comment by dabreegster** [comment]
I also wound up wanting to switch maps without having to create a blank scenario, so I made a call to load a map with an empty simulation. Example [here](https://github.com/dabreegster/urban_observatory_abst/blob/c96847fce3aa66a3c37e1fb293bb5c3939aa9a91/main.py#L65)
