### ISSUE TITLE
Detect existing modal filters from OSM

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#851]
In #822, I made a choice to draw tiny green cells around "car-free" roads. But while modeling Levenshulme in #848, most of the filters on officially provided maps are already existing, and spotting the green cells is really hard. I want to instead just show filters normally in the LTN tool -- meaning they can also be removed or adjusted.

Because the main map model still doesn't have a representation for filters, I think the next step is just in the LTN tool:

1) Detect the tiny road segments that really represent filters
2) Apply map edits to draw them as a normal residential road, with fixed lane configuration (bidi, sidewalk, 1 lane each direction)
3) Initially seed a filter in the middle of that segment

A complication will come from the "pathfinding before changes" case. The contraction hierarchy is built assuming the cycleway segments. To keep representing "before", we actually do want to keep that. But if we transform the map and keep the old pathfinder, will anything break?

Detection should be simpleish... `highway=cycleway`, not one-way, length less than 20 meters, both ends connect to a driveable road.

Some cases that SHOULD be detected:
- https://www.openstreetmap.org/way/4356984
- https://www.openstreetmap.org/way/8158151
- https://www.openstreetmap.org/way/83076987

Some cases that shouldn't count:
- https://www.openstreetmap.org/way/392685069   highway = footway, there's not physically space for a car!
- https://www.openstreetmap.org/way/1002273098  this pattern of 3 parallel roads is often used in London. Easy way to detect is `oneway = yes`

**Comment by dabreegster** [comment]
Started, but false positives..
- https://www.openstreetmap.org/node/4603472923. Require at least one end to be a degenerate intersection?
- Poundbury has a filter on a boundary road! https://www.openstreetmap.org/way/284966542   Well, it's picked up as a boundary road because of blockfinding

Yak-shaving... it's hard to validate, because it's hard to see filters zoomed out and tedious to get OSM debug info

**Comment by dabreegster** [comment]
I just merged an initial version of this. I couldn't spot any false positives (thinking something is a modal filter incorrectly), but there are probably some false negatives, based on the rules defined here:
https://github.com/a-b-street/abstreet/blob/3de1ab3d9de8f3e90666987bcd22c5628ad3d836/ltn/src/filters/existing.rs#L79

If anyone spots any problems either way, please point them out!

@Robinlovelace, existing modal filters are now represented in the tool immediately:
![Screenshot from 2022-02-09 16-01-11](https://user-images.githubusercontent.com/1664407/153239682-1771c3ae-2e1d-460d-be67-2619bc70c8b0.png)

**Comment by Robinlovelace** [comment]
> @Robinlovelace, existing modal filters are now represented in the tool immediately:

Seriously impressive. I like the simple yet effective visualisation of modal filters, the key intervention in LTNs.

**Comment by dabreegster** [comment]
Until we find a false positive or negative, nothing to do here, I think this basically works
