### ISSUE TITLE
Simulate a full day of São Miguel Paulista

### ISSUE THREAD

**Issue by lucasccdias** [a-b-street/abstreet#861]
Hi, @dabreegster .

A/B Street closes everytime I try to upload a large scenario file in a specific area.

Here are the files links:

- [area](https://drive.google.com/file/d/1uzIL1KusjUsboZ0_SGbr9c-pdapF0XWm/view?usp=sharing)
- [scenario](https://drive.google.com/file/d/1M_dDNV3JtG6uefj5E-i-uCgOPYBtKesl/view?usp=sharing)

**Comment by dabreegster** [comment]
The scenario file has negative departure times, like `"departure": -16213837`

I'll make the JSON import reject this upfront. Is it clear how/why the jittered times on your end wound up negative?

**Comment by lucasccdias** [comment]
Here is the fixed [scenario](https://drive.google.com/file/d/1M_dDNV3JtG6uefj5E-i-uCgOPYBtKesl/view?usp=sharing)

**Comment by dabreegster** [comment]
Thanks! I'm going to repurpose this issue for tracking how we can run a full day without gridlocking.

First thing that helps is disabling parking. We have no data about parking capacity in the area, and it's really small, so let's just not simulate it. You can run the main executable with `--infinite-parking`, or I'll consider always enabling it for this map.

Then things generally get stuck around 6:30. An example problem:
![screencast](https://user-images.githubusercontent.com/1664407/154798812-26c95f92-a201-4a36-b816-144bdcf4481c.gif)
A huge volume of pedestrians is crossing here, making the vehicles get stuck. #517 discusses more realistic rules for when people will cross the street.

Just to see how things go without foot/vehicle traffic mixing, I canceled all walking / transit trips:
![Screenshot from 2022-02-19 11-25-01](https://user-images.githubusercontent.com/1664407/154798856-13b26180-93fb-4213-86e2-224f4256bf6e.png)
Things flow pretty well until about 6:30pm:
![Screenshot from 2022-02-19 11-26-40](https://user-images.githubusercontent.com/1664407/154798880-81b2499d-42e4-4041-8d5d-219d9b2a01a9.png)
But ultimately gridlock

**Comment by dabreegster** [comment]
If you build from latest git, when you download the São Paulo region, you'll now get a scenario that fully completes! Let's say you make some change, like adding a bus lane:
![Screenshot from 2022-02-21 21-20-25](https://user-images.githubusercontent.com/1664407/155027585-524fe441-2bd3-4001-8255-61026c7f113a.png)

When you run the simulation, you'll now have all the "A/B testing" features enabled to compare the current simulation to this "prebaked" version before any edits. Namely the "Travel times" dashboard:
![Screenshot from 2022-02-21 21-21-46](https://user-images.githubusercontent.com/1664407/155027744-44e883b0-297a-403c-a4a9-21c537b87dbc.png)
At the bottom of that screen, there's an "Export to CSV" button. The results for my edit above:
[trip_times_br_sao_paulo_sao_miguel_paulista_25h15m23.7s.csv](https://github.com/a-b-street/abstreet/files/8112134/trip_times_br_sao_paulo_sao_miguel_paulista_25h15m23.7s.csv)

Keep in mind that all the results from the simulation, and especially this "some trips got faster/slower" thing, is extremely sensitive to all the things that make A/B Street unrealistic right now. In this area, still the main problem is that drivers wait for pedestrians to cross for an absurdly long time. (#517) But if you like, you can now watch individual trips that get much faster/slower, and use all the A/B testing tools to diagnose why.

**Comment by lucasccdias** [comment]
@dabreegster , how do I "prebake" a custom scenario? The scenario loaded produces a lot of gridlocks when I include a bus lane, for example. I would like to prebake a scenario with just 20% of all trips. I tried modifying `./importer/sao_miguel_paulista_scenario.sh` and it works: it produces the scenario I want. However I could not do the same with the prebaked one. I tried to compile the game again after that and also remove the files and their entries in the `manifest.json` (I imagined that some kind of build automation tool would not find them and would produce them). But it did not work.

**Comment by dabreegster** [comment]
I just added a command to prebake any scenario:

```
cargo run --release --bin cli -- prebake-scenario data/system/br/sao_paulo/scenarios/sao_miguel_paulista/Full.bin
```

Unless this crashes, it should write a file `data/system/br/sao_paulo/prebaked_results/sao_miguel_paulista/Full.bin`, and then the UI will see that.

> I imagined that some kind of build automation tool would not find them and would produce them

A good guess -- that's the aspiration, but there's unfortunately not build automation for everything yet. If you're curious, `data/regen.sh` is the closest thing, but it's a very blunt instrument -- you have to know a few tricks to regenerate individual things. That script regenerates _everything_.

**Comment by dabreegster** [comment]
I also disabled parking for this map; it's only a distraction. The baseline prebaked data changed, so you can either run the updater, or just delete the files and let the UI download them again.

**Comment by lucasccdias** [comment]
Working perfectly! Thanks again!

**Comment by dabreegster** [comment]
Awesome! I'll close this issue (helps me manage my TODO list), but reopen if there's something else we need to do here
