### ISSUE TITLE
LTN Modal filter doesn't work anymore on 3 street intersection (T junction type)

### ISSUE THREAD

**Issue by XaranDeBruregor** [a-b-street/abstreet#862]
Hi ! 

I noticed that modal filter on LTN intersection was bugged with version v0_3_12 (also in v0_3_11). 
I can't place the modal filter. 
So far it's still working with 4 streets intersection. 
![image](https://user-images.githubusercontent.com/98983847/155020148-09640001-e187-4379-b39f-7f14fd9583d7.png)

On the other side, arrows to indicate one way steets are very handy ! Bravo !

**Comment by dabreegster** [comment]
The diagonal filters are only meant to work on 4-way intersections right now. For 3-ways, you can add a filter at the end of the 3 streets to create the desired effect, like:
![Screenshot from 2022-02-22 09-49-47](https://user-images.githubusercontent.com/1664407/155107068-38222b6b-cfe3-4951-a421-1016551c293b.png)
or
![Screenshot from 2022-02-22 09-50-53](https://user-images.githubusercontent.com/1664407/155107119-b3d7364a-5fb2-41f1-b84e-9d7c69d711d3.png)

But you're not the first person to get confused by this. So I think I'll make clicking the 3-way intersections work too, and just toggle between these 2 different possibilities.

(I haven't forgotten about #857 by the way -- thanks for the ideas there, I just need to take a break from hard problems like that for a while, or I burn out)

**Comment by XaranDeBruregor** [comment]
Oh you're absolutely right ! I didn't thought this way. 
Either way to do it is fine. 
(Take care of yourself and don't burn out)

**Comment by dabreegster** [comment]
I'll keep this open for tracking; I do still want to make clicking a 3-way intersection place filters at the edges of roads.

**Comment by dabreegster** [comment]
https://user-images.githubusercontent.com/1664407/156788626-25617a4f-1b39-4849-9b3d-74aa1cccece7.mp4

Sorry this took so long! If you click any non-4 way intersection, it cycles through adding a filter to the end of each connecting road. That's the most intuitive thing I think

**Comment by Robinlovelace** [comment]
Looks so cool from the vid above. Amazing work Dustin!
