### ISSUE TITLE
LTN freehand filter draw needs to handle intersections

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#875]
Yesterday @Robinlovelace used the freehand tool to add filters across a cell, and failed to split it, by deftly managing to cross an intersection polygon instead of a road. The tool should be smarter and pick the road center line closest to the drawn line

**Comment by Robinlovelace** [comment]
Great fix, many thanks for the heads-up, and cannot wait to try out the next release. Greetings from Northwest Wales!

**Comment by dabreegster** [comment]
It won't do the thing you expect for diagonal filters every time, but it'll at least try. Enjoy Wales!
