### ISSUE TITLE
Updating map data from OSM

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#877]
@ThomasDagier, @omalaspinas, and Varad have all recently hit the same problem. After importing an area into A/B Street, they're trying to edit OSM and fix lane tagging, and see the results quickly. There's no nice way to do it today.

Approaches today:
- Delete the .osm.pbf file from data/input and re-import, forcing a fresh Geofabrik download
- Import a custom area, which uses Overpass

Ideal UX is just to click a button to refresh data for the current map. How could it work?

- if the osm.pbf is > 1 day old, first grab geofabrik
- use `osmupdate` to catch it up

Hmm... maybe a simpler approach is just to go through the existing custom import flow using overpass, but feed it the polygon boundary and options from the current map. Actually this sounds easy to implement quickly. Overpass replication delay seemed to be around 10-15 minutes based on a test today

**Comment by dabreegster** [comment]
![Screenshot from 2022-03-11 16-59-26](https://user-images.githubusercontent.com/1664407/157912922-022dcdba-1300-4d4b-82fd-bc22337d621f.png)
Fixed, kind of. In the "pick a city" screen, there's a new button to refresh data for the current map. Few minutes delay between OSM edits and Overpass. Good enough for now. It'll be in this Sunday's build for @darthvarad, or could be used ASAP by @thomasdgr.

**Comment by Robinlovelace** [comment]
:fire:

**Comment by darthvarad** [comment]
Thanks for this, looking forward to Sunday!
