### ISSUE TITLE
Running abstreet on macOS

### ISSUE THREAD

**Issue by jamesneb** [a-b-street/abstreet#882]
Hey guys,

Let me start off by saying that I think this is a really exciting project.

 I am a simulation engineer and I've spent most of my career in the material handling and logistics space - both designing simulations and using statistical methods to analyze them. I am currently in the process of learning Rust, and when I am able, I would love to contribute to this project.

Now for my issue. I am unable to run the program effectively from my 2019 Macbook Pro running macOS Monterey 12.1. When running: 

```cargo run --bin updater -- download -- minimal```

It mostly works but at the end I receive this error:

``` error: Found argument 'minimal' which wasn't expected, or isn't valid in this context ```

Then, when I attempt to run the application with:

```  cargo run --bin game ```

I receive an error complaining that /data/system/us/seattle/maps/montlake.bin could not be loaded. Upon further investigation, it seems no maps have been loaded to my *system* subdirectory at all.

How do I proceed?

**Comment by michaelkirk** [comment]
I’m responding from mobile, so I might be wrong, but:

I think the second command, to run the game, is failing because the first command, which downloads requisite data, failed.

I think the first command failed because you have a space before “minimal” between the double dashes, try “--minimal”

**Comment by jamesneb** [comment]
Aha! 🤓 thank you.
