### ISSUE TITLE
Expand study area for Sao Miguel Paulista in Sao Paulo, Brazil

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstreet#903]
Currently the study area is v. small: http://play.abstreet.org/0.3.19/abstreet.html?system/br/sao_paulo/scenarios/sao_miguel_paulista/home_to_work.bin&--cam=16.96/-23.49414/-46.44084

![image](https://user-images.githubusercontent.com/1825120/165778501-e3dd000d-2986-4dc8-bc46-b9c6ca335adb.png)

Although the area is correct, the simulations will be more interesting if we show a bigger area. Preliminary suggestion, expand it by 2000 m. Would it be better to expand it by more than that?

Also documented in https://github.com/spstreets/OD2017/issues/29 and heads-up @lucasccdias who's up for this mission I think, many thanks!

**Comment by Robinlovelace** [comment]
Great to see busses in there now btw.

**Comment by dabreegster** [comment]
Keep in mind the larger the area, the more bugs we invite. :)  We can try it. Would it be possible to get help from somebody familiar with the area in checking over lane tagging (like are there sidewalks on both sides of a one-way street)? It's harder to glance at satellite of an unfamiliar place and quickly know what's on the ground. If it's easiest, these fixes could be done in A/B Street, and I can go put them in OSM.

**Comment by Robinlovelace** [comment]
Maybe start with 500 m first then?

**Comment by dabreegster** [comment]
Closing this old issue. I had tried this and it introduced more complications into the already brittle traffic sim results, so decided to keep the original area. Notes are unfortunately in Discord or an email somewhere. :\  But this project isn't active, so closing
