### ISSUE TITLE
Panic during tutorial pause/resume stage

### ISSUE THREAD

**Issue by earthspike** [a-b-street/abstreet#914]
panicked at 'called `Result::unwrap()` on an `Err` value: Can't find OriginalRoad(https://www.openstreetmap.org/way/158782224 from https://www.openstreetmap.org/node/1709145066 to https://www.openstreetmap.org/node/53128052', apps/game/src/sandbox/gameplay/tutorial.rs:1058:30

Ubuntu Linux 20.04 LTS,  x86_64,  Firefox 99.0

**Comment by earthspike** [comment]
I can reproduce this by reloading the page, going to the tutorial, skipping straight to task 4, then pressing the space bar a few times.

**Comment by earthspike** [comment]
And if I skip straight to task 5 it crashes as well. URL for all of these is http://play.abstreet.org/0.3.20/abstreet.html?--cam=18.69/47.64246/-122.31883.

**Comment by dabreegster** [comment]
Thanks for the detailed bug report! I had updated Seattle OpenStreetMap data last week and forgot to check some hardcoded IDs in the tutorial. I quickly went through it again, and everything seems to work as before. The fix will be released tomorrow.
