### ISSUE TITLE
Try out lyon 1.0

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#954]
https://nical.github.io/posts/lyon-1-0.html  (Congrats on the release, if maintainers ever happen to see this)

1) The variable width strokes could be an interesting experiment for roads that change width in the middle. (The direct math in `PolyLine::make_polygons` probably wouldn't be too hard to extend to do this, but lyon also has bezier curves. CC @BudgieInWA as FYI, I know you've been interested in using those)

2) The path sampler sounds like it could possibly replace `PolyLine::dist_along`. I may want to try out the acceleration structure in `bus_spotting` particularly

**Comment by dabreegster** [comment]
Blocked on https://github.com/nical/lyon/issues/806

**Comment by Robinlovelace** [comment]
:fire:
