### ISSUE TITLE
Be careful with private roads in the LTN tool

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#968]
Near https://www.openstreetmap.org/way/30197992 (`highway=service, access=private`), we have...

https://user-images.githubusercontent.com/1664407/185182944-cfbdc8eb-c834-4738-b44e-c9e4959203cb.mp4

This is quite the false positive, since this is a service road near a prison

**Comment by Robinlovelace** [comment]
> This is quite the false positive, since this is a service road near a prison

Not too many people going in or out then!

**Comment by dabreegster** [comment]
![Screenshot from 2022-08-24 13-14-29](https://user-images.githubusercontent.com/1664407/186415595-a9ba5d94-86ff-4d51-aeb8-fac4e75e0710.png)
The shortcut is exiting the area and re-entering. It does a funny U-turn on Wellington Mews. This is the only way that particular path can be satisfied; the B intersection is the one at the prison entrance.

I thought I remember filtering out shortcuts that leave and re-enter. Looking into that first. Also want to re-think service roads generally, but that doesn't look like the actual bug here.

**Comment by dabreegster** [comment]
Yup, one problem fixed. https://www.openstreetmap.org/way/136946798 still has some shortcutting, but it has `access=private`. The LTN tool should treat those as totally impassable (even for cell calculations). Working on that now...
![Screenshot from 2022-08-24 13-28-29](https://user-images.githubusercontent.com/1664407/186418505-b08f41c0-d350-4ca1-bcf6-cfb8df6b9a69.png)

**Comment by dabreegster** [comment]
I think things're good enough for now. It'd be nice to pick up `barrier=gate` and similar and show a filter, but I'll leave that for future work. If anyone hits more problems here and it's not just missing data in OSM, I'll reopen
