### ISSUE TITLE
Mac bug: ColorSync dyld

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#99]
```
dyld: Library not loaded: /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
  Referenced from: Downloads/abstreet_mac_v0_2_0a/game/./game
  Reason: image not found
```

I don't know why this utility is being linked? I'm guessing the person hitting this problem is on Mac older than 10.15, which is what Github builds against: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

Anybody with Mac knowledge know how to help?

**Comment by michaelkirk** [comment]
ColorSync is supported as of 10.13 (High Sierra)

https://developer.apple.com/documentation/colorsync

Do you know what version they were running?

**Comment by dabreegster** [comment]
From an email, 10.12. I'll let them know that upgrading should work. I guess we should start that minimum system requirements document?
