### ISSUE TITLE
App crash at startup of Low-traffic neighborhoods tool in browser

### ISSUE THREAD

**Issue by ChronicAdrift** [a-b-street/abstreet#991]
When wanting to try out the Low-traffic neighborhoods tool in the browser, by using the [link](https://a-b-street.github.io/docs/software/ltn/index.html) in the documentation [`http://play.abstreet.org/0.3.33/ltn.html?system/gb/bristol/maps/east.bin`](http://play.abstreet.org/0.3.33/ltn.html?system/gb/bristol/maps/east.bin), the web app crashes with the following error.
```
panicked at 'Bad Pt2D inf, inf', geom/src/pt.rs:30:13
```
In contrast [`http://play.abstreet.org/0.3.33/abstreet.html?--ungap&system/us/seattle/maps/central_seattle.bin`](http://play.abstreet.org/0.3.33/abstreet.html?--ungap&system/us/seattle/maps/central_seattle.bin) works.
With a changed map [`http://play.abstreet.org/0.3.33/ltn.html?system/us/seattle/maps/central_seattle.bin`](http://play.abstreet.org/0.3.33/ltn.html?system/us/seattle/maps/central_seattle.bin) also breaks with the same error.

I am running Firefox on Ubuntu, 104.0 (64-bit) from canonical 1.0.

**Comment by dabreegster** [comment]
Thanks for reporting! I can't reproduce this. Did it happen immediately the first time you loaded, or after you moved the map or zoomed a bit? Did the error message have a longer stack trace? Or could you open the developer console (control+shift+I, you might have to click on the edge of the window first) and see if there's any more info about the error there?

**Comment by ChronicAdrift** [comment]
It happened immediately after loading and this was the only trace which popped up in a text window.
What is curious to me is that the static DrawMap consumes 0 MB, but this might be correct, anyways the WebGL throws and error shortly afterwards.
```
Started loading WASM [ltn.bundle.js:83:21](http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js)
It took 82 ms to download WASM, now initializing it [ltn.bundle.js:118:21](http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js)
state change: loading -> loaded [ltn.bundle.js:166:17](http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js)
state change: loaded -> starting [ltn.bundle.js:166:17](http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js)
running app with assetsBaseURL: ./data, assetsAreGzipped: true [ltn.bundle.js:132:25](http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [ltn.js:750:35](http://play.abstreet.org/0.3.33/ltn/wasm_pkg/ltn.js)
static DrawMap consumes 0 MB on the GPU [ltn.js:1250:17](http://play.abstreet.org/0.3.33/ltn/wasm_pkg/ltn.js)
Panicked: panicked at 'Bad Pt2D inf, inf', geom/src/pt.rs:30:13 [ltn.js:1244:17](http://play.abstreet.org/0.3.33/ltn/wasm_pkg/ltn.js)
WebGL warning: texStorage(Multisample)?: internalformat: Invalid enum value RGBA [ltn.js:841:25](http://play.abstreet.org/0.3.33/ltn/wasm_pkg/ltn.js)
state change: starting -> error [ltn.bundle.js:166:17](http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js)
Uncaught (in promise) RuntimeError: unreachable executed
    run http://play.abstreet.org/0.3.33/ltn/wasm_pkg/ltn.js:276
    run http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:294
    start http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:133
    __awaiter http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:7
    __awaiter http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:3
    start http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:128
    loadAndStart http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:71
    fulfilled http://play.abstreet.org/0.3.33/ltn/ltn.bundle.js:4
[ltn.js line 536 > WebAssembly.instantiate:5679143:1](http://play.abstreet.org/0.3.33/ltn/wasm_pkg/ltn.js%20line%20536%20%3E%20WebAssembly.instantiate)
```

**Comment by dabreegster** [comment]
I don't think the DrawMap memory estimate and WebGL warnings are relevant / actually a problem... Some bit of math somewhere is dividing by 0 and trying to create a bad point. Usually there's some kind of stack trace that points to where, but maybe it's happening so early that some of that hasn't even been set up yet...

We can figure out if it's the specific map or something in the LTN tool. When the crash happens, do you even get to a loading screen where it downloads the map?
![Screenshot from 2022-09-08 12-38-33](https://user-images.githubusercontent.com/1664407/189113084-0ada53cf-c5bf-43a2-86f0-2d70f8fa5903.png)

Does http://play.abstreet.org/0.3.33/fifteen_min.html?system/gb/bristol/maps/east.bin&--cam=14.43/51.45137/-2.53633 work for you? That's the same Bristol map, but a different tool. Since the main abstreet.html app worked for you, I suspect it might be just the LTN tool. There's stuff like new road label rendering there that might be dividing by 0 in some weird edge case...

**Comment by ChronicAdrift** [comment]
Just a blackscreen with white borders is what I get.
Yes, I think it is the LTN tool. The other application you linked now works just fine.

**Comment by dabreegster** [comment]
Give it another try, please -- I think the problem was the fake/blank map that's temporarily loaded before the real map loads. For some reason the real map loads fast enough on Firefox and Chrome for me, but you and another user seem to be hitting some other case

**Comment by Robinlovelace** [comment]
I cannot reproduce this issue on recent versions of Firefox or Chrome.

**Comment by dabreegster** [comment]
Someone else confirmed this is fixed, so I'm going to assume we're good. Please reopen if not!

**Comment by ChronicAdrift** [comment]
Works for me now as well, thank you!
